// آل شايع Family Data - 99 members across 8 generations
// This can be replaced with Prisma database queries when available

export interface FamilyMember {
  id: string;
  firstName: string;
  fatherName: string | null;
  grandfatherName: string | null;
  greatGrandfatherName: string | null;
  familyName: string;
  fatherId: string | null;
  gender: 'Male' | 'Female';
  birthYear: number | null;
  deathYear?: number | null;
  sonsCount: number;
  daughtersCount: number;
  generation: number;
  branch: string | null;
  fullNameAr: string | null;
  fullNameEn: string | null;
  phone: string | null;
  city: string | null;
  status: string;
  photoUrl: string | null;
  biography: string | null;
  occupation: string | null;
  email: string | null;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: string | null;
  lastModifiedBy?: string | null;
  version?: number;
  // Lineage Identification Fields
  lineageBranchId?: string | null;      // ID of the Gen 2 ancestor (main branch founder)
  lineageBranchName?: string | null;    // Name of the Gen 2 ancestor for display
  subBranchId?: string | null;          // ID of the Gen 3 ancestor (sub-branch founder)
  subBranchName?: string | null;        // Name of the Gen 3 ancestor for display
  lineagePath?: string[] | null;        // Array of ancestor IDs from root to parent
}

export const familyMembers: FamilyMember[] = [
  // Generation 1 (Root - الجذر)
  {
    id: 'P001',
    firstName: 'حمد',
    fatherName: null,
    grandfatherName: null,
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: null,
    gender: 'Male',
    birthYear: 1600,
    sonsCount: 3,
    daughtersCount: 0,
    generation: 1,
    branch: 'الأصل',
    fullNameAr: 'حمد آل شايع',
    fullNameEn: 'Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },

  // Generation 2
  {
    id: 'P002',
    firstName: 'ابراهيم',
    fatherName: 'حمد',
    grandfatherName: null,
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P001',
    gender: 'Male',
    birthYear: 1630,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 2,
    branch: 'الأصل',
    fullNameAr: 'ابراهيم بن حمد آل شايع',
    fullNameEn: 'Ibrahim bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P003',
    firstName: 'عبدالكريم',
    fatherName: 'حمد',
    grandfatherName: null,
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P001',
    gender: 'Male',
    birthYear: 1635,
    sonsCount: 2,
    daughtersCount: 1,
    generation: 2,
    branch: 'الأصل',
    fullNameAr: 'عبدالكريم بن حمد آل شايع',
    fullNameEn: 'Abdulkareem bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P004',
    firstName: 'فوزان',
    fatherName: 'حمد',
    grandfatherName: null,
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P001',
    gender: 'Male',
    birthYear: 1640,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 2,
    branch: 'الفرع 1',
    fullNameAr: 'فوزان بن حمد آل شايع',
    fullNameEn: 'Fawzan bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },

  // Generation 3
  {
    id: 'P005',
    firstName: 'محمد',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P002',
    gender: 'Male',
    birthYear: 1660,
    sonsCount: 5,
    daughtersCount: 3,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'محمد بن ابراهيم بن حمد آل شايع',
    fullNameEn: 'Mohammed bin Ibrahim bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P006',
    firstName: 'ناصر',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P002',
    gender: 'Male',
    birthYear: 1665,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'ناصر بن ابراهيم بن حمد آل شايع',
    fullNameEn: 'Nasser bin Ibrahim bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P007',
    firstName: 'عبدالله',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P002',
    gender: 'Male',
    birthYear: 1670,
    sonsCount: 3,
    daughtersCount: 4,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'عبدالله بن ابراهيم بن حمد آل شايع',
    fullNameEn: 'Abdullah bin Ibrahim bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P008',
    firstName: 'فاطمة',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P002',
    gender: 'Female',
    birthYear: 1668,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'فاطمة بنت ابراهيم بن حمد آل شايع',
    fullNameEn: 'Fatima bint Ibrahim bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P009',
    firstName: 'نورة',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P002',
    gender: 'Female',
    birthYear: 1672,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'نورة بنت ابراهيم بن حمد آل شايع',
    fullNameEn: 'Noura bint Ibrahim bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P010',
    firstName: 'سعود',
    fatherName: 'عبدالكريم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P003',
    gender: 'Male',
    birthYear: 1665,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'سعود بن عبدالكريم بن حمد آل شايع',
    fullNameEn: 'Saud bin Abdulkareem bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P011',
    firstName: 'خالد',
    fatherName: 'عبدالكريم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P003',
    gender: 'Male',
    birthYear: 1670,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'خالد بن عبدالكريم بن حمد آل شايع',
    fullNameEn: 'Khalid bin Abdulkareem bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P012',
    firstName: 'موضي',
    fatherName: 'عبدالكريم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P003',
    gender: 'Female',
    birthYear: 1668,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'موضي بنت عبدالكريم بن حمد آل شايع',
    fullNameEn: 'Moudi bint Abdulkareem bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P013',
    firstName: 'سلمان',
    fatherName: 'فوزان',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P004',
    gender: 'Male',
    birthYear: 1670,
    sonsCount: 5,
    daughtersCount: 2,
    generation: 3,
    branch: 'الفرع 1',
    fullNameAr: 'سلمان بن فوزان بن حمد آل شايع',
    fullNameEn: 'Salman bin Fawzan bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P014',
    firstName: 'تركي',
    fatherName: 'فوزان',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P004',
    gender: 'Male',
    birthYear: 1675,
    sonsCount: 3,
    daughtersCount: 4,
    generation: 3,
    branch: 'الفرع 1',
    fullNameAr: 'تركي بن فوزان بن حمد آل شايع',
    fullNameEn: 'Turki bin Fawzan bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P015',
    firstName: 'منيرة',
    fatherName: 'فوزان',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    familyName: 'آل شايع',
    fatherId: 'P004',
    gender: 'Female',
    birthYear: 1672,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 3,
    branch: 'الفرع 1',
    fullNameAr: 'منيرة بنت فوزان بن حمد آل شايع',
    fullNameEn: 'Munira bint Fawzan bin Hamad Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },

  // Generation 4
  {
    id: 'P016',
    firstName: 'ابراهيم',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P005',
    gender: 'Male',
    birthYear: 1890,
    sonsCount: 5,
    daughtersCount: 3,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'ابراهيم بن محمد بن ابراهيم آل شايع',
    fullNameEn: 'Ibrahim bin Mohammed bin Ibrahim Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P017',
    firstName: 'عبدالمحسن',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P005',
    gender: 'Male',
    birthYear: 1895,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'عبدالمحسن بن محمد بن ابراهيم آل شايع',
    fullNameEn: 'Abdulmohsen bin Mohammed bin Ibrahim Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P018',
    firstName: 'عبدالرحمن',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P005',
    gender: 'Male',
    birthYear: 1900,
    sonsCount: 6,
    daughtersCount: 4,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'عبدالرحمن بن محمد بن ابراهيم آل شايع',
    fullNameEn: 'Abdulrahman bin Mohammed bin Ibrahim Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P019',
    firstName: 'صالح',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P005',
    gender: 'Male',
    birthYear: 1905,
    sonsCount: 3,
    daughtersCount: 5,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'صالح بن محمد بن ابراهيم آل شايع',
    fullNameEn: 'Saleh bin Mohammed bin Ibrahim Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P020',
    firstName: 'حصة',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P005',
    gender: 'Female',
    birthYear: 1892,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'حصة بنت محمد بن ابراهيم آل شايع',
    fullNameEn: 'Hessa bint Mohammed bin Ibrahim Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P021',
    firstName: 'أحمد',
    fatherName: 'ناصر',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P006',
    gender: 'Male',
    birthYear: 1895,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'أحمد بن ناصر بن ابراهيم آل شايع',
    fullNameEn: 'Ahmed bin Nasser bin Ibrahim Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P022',
    firstName: 'عبدالعزيز',
    fatherName: 'ناصر',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P006',
    gender: 'Male',
    birthYear: 1900,
    sonsCount: 5,
    daughtersCount: 2,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'عبدالعزيز بن ناصر بن ابراهيم آل شايع',
    fullNameEn: 'Abdulaziz bin Nasser bin Ibrahim Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P023',
    firstName: 'يوسف',
    fatherName: 'سعود',
    grandfatherName: 'عبدالكريم',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P010',
    gender: 'Male',
    birthYear: 1895,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'يوسف بن سعود بن عبدالكريم آل شايع',
    fullNameEn: 'Yousef bin Saud bin Abdulkareem Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P024',
    firstName: 'علي',
    fatherName: 'سلمان',
    grandfatherName: 'فوزان',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P013',
    gender: 'Male',
    birthYear: 1900,
    sonsCount: 5,
    daughtersCount: 4,
    generation: 4,
    branch: 'الفرع 1',
    fullNameAr: 'علي بن سلمان بن فوزان آل شايع',
    fullNameEn: 'Ali bin Salman bin Fawzan Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P025',
    firstName: 'فهد',
    fatherName: 'تركي',
    grandfatherName: 'فوزان',
    greatGrandfatherName: 'حمد',
    familyName: 'آل شايع',
    fatherId: 'P014',
    gender: 'Male',
    birthYear: 1905,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 4,
    branch: 'الفرع 1',
    fullNameAr: 'فهد بن تركي بن فوزان آل شايع',
    fullNameEn: 'Fahad bin Turki bin Fawzan Al-Shaye',
    phone: null,
    city: null,
    status: 'Deceased',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },

  // Generation 5
  {
    id: 'P026',
    firstName: 'سعد',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P016',
    gender: 'Male',
    birthYear: 1935,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'سعد بن ابراهيم بن محمد آل شايع',
    fullNameEn: 'Saad bin Ibrahim bin Mohammed Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P027',
    firstName: 'فيصل',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P016',
    gender: 'Male',
    birthYear: 1940,
    sonsCount: 5,
    daughtersCount: 2,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'فيصل بن ابراهيم بن محمد آل شايع',
    fullNameEn: 'Faisal bin Ibrahim bin Mohammed Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P028',
    firstName: 'بندر',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P016',
    gender: 'Male',
    birthYear: 1945,
    sonsCount: 3,
    daughtersCount: 4,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'بندر بن ابراهيم بن محمد آل شايع',
    fullNameEn: 'Bandar bin Ibrahim bin Mohammed Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P029',
    firstName: 'سارة',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P016',
    gender: 'Female',
    birthYear: 1938,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'سارة بنت ابراهيم بن محمد آل شايع',
    fullNameEn: 'Sarah bint Ibrahim bin Mohammed Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P030',
    firstName: 'مريم',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P016',
    gender: 'Female',
    birthYear: 1942,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'مريم بنت ابراهيم بن محمد آل شايع',
    fullNameEn: 'Mariam bint Ibrahim bin Mohammed Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P031',
    firstName: 'ماجد',
    fatherName: 'عبدالمحسن',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P017',
    gender: 'Male',
    birthYear: 1940,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'ماجد بن عبدالمحسن بن محمد آل شايع',
    fullNameEn: 'Majed bin Abdulmohsen bin Mohammed Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P032',
    firstName: 'وليد',
    fatherName: 'عبدالرحمن',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P018',
    gender: 'Male',
    birthYear: 1945,
    sonsCount: 5,
    daughtersCount: 3,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'وليد بن عبدالرحمن بن محمد آل شايع',
    fullNameEn: 'Waleed bin Abdulrahman bin Mohammed Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P033',
    firstName: 'طلال',
    fatherName: 'أحمد',
    grandfatherName: 'ناصر',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P021',
    gender: 'Male',
    birthYear: 1940,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'طلال بن أحمد بن ناصر آل شايع',
    fullNameEn: 'Talal bin Ahmed bin Nasser Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P034',
    firstName: 'نواف',
    fatherName: 'عبدالعزيز',
    grandfatherName: 'ناصر',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P022',
    gender: 'Male',
    birthYear: 1945,
    sonsCount: 5,
    daughtersCount: 4,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'نواف بن عبدالعزيز بن ناصر آل شايع',
    fullNameEn: 'Nawaf bin Abdulaziz bin Nasser Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P035',
    firstName: 'حسن',
    fatherName: 'يوسف',
    grandfatherName: 'سعود',
    greatGrandfatherName: 'عبدالكريم',
    familyName: 'آل شايع',
    fatherId: 'P023',
    gender: 'Male',
    birthYear: 1940,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'حسن بن يوسف بن سعود آل شايع',
    fullNameEn: 'Hassan bin Yousef bin Saud Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P036',
    firstName: 'عمر',
    fatherName: 'علي',
    grandfatherName: 'سلمان',
    greatGrandfatherName: 'فوزان',
    familyName: 'آل شايع',
    fatherId: 'P024',
    gender: 'Male',
    birthYear: 1945,
    sonsCount: 5,
    daughtersCount: 3,
    generation: 5,
    branch: 'الفرع 1',
    fullNameAr: 'عمر بن علي بن سلمان آل شايع',
    fullNameEn: 'Omar bin Ali bin Salman Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P037',
    firstName: 'سلطان',
    fatherName: 'فهد',
    grandfatherName: 'تركي',
    greatGrandfatherName: 'فوزان',
    familyName: 'آل شايع',
    fatherId: 'P025',
    gender: 'Male',
    birthYear: 1950,
    sonsCount: 4,
    daughtersCount: 4,
    generation: 5,
    branch: 'الفرع 1',
    fullNameAr: 'سلطان بن فهد بن تركي آل شايع',
    fullNameEn: 'Sultan bin Fahad bin Turki Al-Shaye',
    phone: null,
    city: null,
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },

  // Generation 6
  {
    id: 'P038',
    firstName: 'خالد',
    fatherName: 'سعد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P026',
    gender: 'Male',
    birthYear: 1965,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'خالد بن سعد بن ابراهيم آل شايع',
    fullNameEn: 'Khalid bin Saad bin Ibrahim Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مهندس',
    email: null,
  },
  {
    id: 'P039',
    firstName: 'محمد',
    fatherName: 'سعد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P026',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'محمد بن سعد بن ابراهيم آل شايع',
    fullNameEn: 'Mohammed bin Saad bin Ibrahim Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طبيب',
    email: null,
  },
  {
    id: 'P040',
    firstName: 'عبدالله',
    fatherName: 'فيصل',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P027',
    gender: 'Male',
    birthYear: 1970,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'عبدالله بن فيصل بن ابراهيم آل شايع',
    fullNameEn: 'Abdullah bin Faisal bin Ibrahim Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'رجل أعمال',
    email: null,
  },
  {
    id: 'P041',
    firstName: 'أمل',
    fatherName: 'فيصل',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P027',
    gender: 'Female',
    birthYear: 1972,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'أمل بنت فيصل بن ابراهيم آل شايع',
    fullNameEn: 'Amal bint Faisal bin Ibrahim Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'معلمة',
    email: null,
  },
  {
    id: 'P042',
    firstName: 'عادل',
    fatherName: 'بندر',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P028',
    gender: 'Male',
    birthYear: 1975,
    sonsCount: 2,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'عادل بن بندر بن ابراهيم آل شايع',
    fullNameEn: 'Adel bin Bandar bin Ibrahim Al-Shaye',
    phone: null,
    city: 'الدمام',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'محاسب',
    email: null,
  },
  {
    id: 'P043',
    firstName: 'ريم',
    fatherName: 'ماجد',
    grandfatherName: 'عبدالمحسن',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P031',
    gender: 'Female',
    birthYear: 1970,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'ريم بنت ماجد بن عبدالمحسن آل شايع',
    fullNameEn: 'Reem bint Majed bin Abdulmohsen Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طبيبة',
    email: null,
  },
  {
    id: 'P044',
    firstName: 'فارس',
    fatherName: 'وليد',
    grandfatherName: 'عبدالرحمن',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P032',
    gender: 'Male',
    birthYear: 1975,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'فارس بن وليد بن عبدالرحمن آل شايع',
    fullNameEn: 'Fares bin Waleed bin Abdulrahman Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مهندس',
    email: null,
  },
  {
    id: 'P045',
    firstName: 'يزيد',
    fatherName: 'طلال',
    grandfatherName: 'أحمد',
    greatGrandfatherName: 'ناصر',
    familyName: 'آل شايع',
    fatherId: 'P033',
    gender: 'Male',
    birthYear: 1970,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'يزيد بن طلال بن أحمد آل شايع',
    fullNameEn: 'Yazeed bin Talal bin Ahmed Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طيار',
    email: null,
  },
  {
    id: 'P046',
    firstName: 'تركي',
    fatherName: 'نواف',
    grandfatherName: 'عبدالعزيز',
    greatGrandfatherName: 'ناصر',
    familyName: 'آل شايع',
    fatherId: 'P034',
    gender: 'Male',
    birthYear: 1975,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'تركي بن نواف بن عبدالعزيز آل شايع',
    fullNameEn: 'Turki bin Nawaf bin Abdulaziz Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'محامي',
    email: null,
  },
  {
    id: 'P047',
    firstName: 'مشاري',
    fatherName: 'حسن',
    grandfatherName: 'يوسف',
    greatGrandfatherName: 'سعود',
    familyName: 'آل شايع',
    fatherId: 'P035',
    gender: 'Male',
    birthYear: 1970,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'مشاري بن حسن بن يوسف آل شايع',
    fullNameEn: 'Mishari bin Hassan bin Yousef Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مهندس معماري',
    email: null,
  },
  {
    id: 'P048',
    firstName: 'راكان',
    fatherName: 'عمر',
    grandfatherName: 'علي',
    greatGrandfatherName: 'سلمان',
    familyName: 'آل شايع',
    fatherId: 'P036',
    gender: 'Male',
    birthYear: 1975,
    sonsCount: 3,
    daughtersCount: 4,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'راكان بن عمر بن علي آل شايع',
    fullNameEn: 'Rakan bin Omar bin Ali Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مدير تنفيذي',
    email: null,
  },
  {
    id: 'P049',
    firstName: 'دانة',
    fatherName: 'سلطان',
    grandfatherName: 'فهد',
    greatGrandfatherName: 'تركي',
    familyName: 'آل شايع',
    fatherId: 'P037',
    gender: 'Female',
    birthYear: 1980,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'دانة بنت سلطان بن فهد آل شايع',
    fullNameEn: 'Dana bint Sultan bin Fahad Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مصممة',
    email: null,
  },

  // Generation 7
  {
    id: 'P050',
    firstName: 'عبدالرحمن',
    fatherName: 'خالد',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P038',
    gender: 'Male',
    birthYear: 1990,
    sonsCount: 2,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'عبدالرحمن بن خالد بن سعد آل شايع',
    fullNameEn: 'Abdulrahman bin Khalid bin Saad Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مبرمج',
    email: null,
  },
  {
    id: 'P051',
    firstName: 'سلمى',
    fatherName: 'خالد',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P038',
    gender: 'Female',
    birthYear: 1992,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'سلمى بنت خالد بن سعد آل شايع',
    fullNameEn: 'Salma bint Khalid bin Saad Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مهندسة',
    email: null,
  },
  {
    id: 'P052',
    firstName: 'ناصر',
    fatherName: 'محمد',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P039',
    gender: 'Male',
    birthYear: 1993,
    sonsCount: 1,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'ناصر بن محمد بن سعد آل شايع',
    fullNameEn: 'Nasser bin Mohammed bin Saad Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طبيب أسنان',
    email: null,
  },
  {
    id: 'P053',
    firstName: 'لمى',
    fatherName: 'محمد',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P039',
    gender: 'Female',
    birthYear: 1995,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'لمى بنت محمد بن سعد آل شايع',
    fullNameEn: 'Lama bint Mohammed bin Saad Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'صيدلانية',
    email: null,
  },
  {
    id: 'P054',
    firstName: 'فهد',
    fatherName: 'عبدالله',
    grandfatherName: 'فيصل',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P040',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'فهد بن عبدالله بن فيصل آل شايع',
    fullNameEn: 'Fahad bin Abdullah bin Faisal Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'رائد أعمال',
    email: null,
  },
  {
    id: 'P055',
    firstName: 'نورة',
    fatherName: 'عبدالله',
    grandfatherName: 'فيصل',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P040',
    gender: 'Female',
    birthYear: 1997,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'نورة بنت عبدالله بن فيصل آل شايع',
    fullNameEn: 'Noura bint Abdullah bin Faisal Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالبة جامعية',
    email: null,
  },
  {
    id: 'P056',
    firstName: 'سعود',
    fatherName: 'عادل',
    grandfatherName: 'بندر',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P042',
    gender: 'Male',
    birthYear: 2000,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'سعود بن عادل بن بندر آل شايع',
    fullNameEn: 'Saud bin Adel bin Bandar Al-Shaye',
    phone: null,
    city: 'الدمام',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالب جامعي',
    email: null,
  },
  {
    id: 'P057',
    firstName: 'جود',
    fatherName: 'عادل',
    grandfatherName: 'بندر',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P042',
    gender: 'Female',
    birthYear: 2002,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'جود بنت عادل بن بندر آل شايع',
    fullNameEn: 'Joud bint Adel bin Bandar Al-Shaye',
    phone: null,
    city: 'الدمام',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالبة',
    email: null,
  },
  {
    id: 'P058',
    firstName: 'حمد',
    fatherName: 'فارس',
    grandfatherName: 'وليد',
    greatGrandfatherName: 'عبدالرحمن',
    familyName: 'آل شايع',
    fatherId: 'P044',
    gender: 'Male',
    birthYear: 2000,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'حمد بن فارس بن وليد آل شايع',
    fullNameEn: 'Hamad bin Fares bin Waleed Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالب جامعي',
    email: null,
  },
  {
    id: 'P059',
    firstName: 'لين',
    fatherName: 'فارس',
    grandfatherName: 'وليد',
    greatGrandfatherName: 'عبدالرحمن',
    familyName: 'آل شايع',
    fatherId: 'P044',
    gender: 'Female',
    birthYear: 2002,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'لين بنت فارس بن وليد آل شايع',
    fullNameEn: 'Leen bint Fares bin Waleed Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالبة',
    email: null,
  },
  {
    id: 'P060',
    firstName: 'عبدالعزيز',
    fatherName: 'يزيد',
    grandfatherName: 'طلال',
    greatGrandfatherName: 'أحمد',
    familyName: 'آل شايع',
    fatherId: 'P045',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'عبدالعزيز بن يزيد بن طلال آل شايع',
    fullNameEn: 'Abdulaziz bin Yazeed bin Talal Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طيار',
    email: null,
  },
  {
    id: 'P061',
    firstName: 'ريناد',
    fatherName: 'يزيد',
    grandfatherName: 'طلال',
    greatGrandfatherName: 'أحمد',
    familyName: 'آل شايع',
    fatherId: 'P045',
    gender: 'Female',
    birthYear: 1998,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'ريناد بنت يزيد بن طلال آل شايع',
    fullNameEn: 'Renad bint Yazeed bin Talal Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مصممة جرافيك',
    email: null,
  },
  {
    id: 'P062',
    firstName: 'بدر',
    fatherName: 'تركي',
    grandfatherName: 'نواف',
    greatGrandfatherName: 'عبدالعزيز',
    familyName: 'آل شايع',
    fatherId: 'P046',
    gender: 'Male',
    birthYear: 2000,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'بدر بن تركي بن نواف آل شايع',
    fullNameEn: 'Badr bin Turki bin Nawaf Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالب جامعي',
    email: null,
  },
  {
    id: 'P063',
    firstName: 'غادة',
    fatherName: 'تركي',
    grandfatherName: 'نواف',
    greatGrandfatherName: 'عبدالعزيز',
    familyName: 'آل شايع',
    fatherId: 'P046',
    gender: 'Female',
    birthYear: 2003,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'غادة بنت تركي بن نواف آل شايع',
    fullNameEn: 'Ghada bint Turki bin Nawaf Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالبة',
    email: null,
  },
  {
    id: 'P064',
    firstName: 'زياد',
    fatherName: 'مشاري',
    grandfatherName: 'حسن',
    greatGrandfatherName: 'يوسف',
    familyName: 'آل شايع',
    fatherId: 'P047',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'زياد بن مشاري بن حسن آل شايع',
    fullNameEn: 'Ziyad bin Mishari bin Hassan Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مهندس مدني',
    email: null,
  },
  {
    id: 'P065',
    firstName: 'هيفاء',
    fatherName: 'مشاري',
    grandfatherName: 'حسن',
    greatGrandfatherName: 'يوسف',
    familyName: 'آل شايع',
    fatherId: 'P047',
    gender: 'Female',
    birthYear: 1998,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'هيفاء بنت مشاري بن حسن آل شايع',
    fullNameEn: 'Haifa bint Mishari bin Hassan Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'معلمة',
    email: null,
  },
  {
    id: 'P066',
    firstName: 'عمر',
    fatherName: 'راكان',
    grandfatherName: 'عمر',
    greatGrandfatherName: 'علي',
    familyName: 'آل شايع',
    fatherId: 'P048',
    gender: 'Male',
    birthYear: 2000,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الفرع 1',
    fullNameAr: 'عمر بن راكان بن عمر آل شايع',
    fullNameEn: 'Omar bin Rakan bin Omar Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالب جامعي',
    email: null,
  },
  {
    id: 'P067',
    firstName: 'لجين',
    fatherName: 'راكان',
    grandfatherName: 'عمر',
    greatGrandfatherName: 'علي',
    familyName: 'آل شايع',
    fatherId: 'P048',
    gender: 'Female',
    birthYear: 2002,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الفرع 1',
    fullNameAr: 'لجين بنت راكان بن عمر آل شايع',
    fullNameEn: 'Lujain bint Rakan bin Omar Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالبة',
    email: null,
  },

  // Generation 8 (youngest)
  {
    id: 'P068',
    firstName: 'سلطان',
    fatherName: 'عبدالرحمن',
    grandfatherName: 'خالد',
    greatGrandfatherName: 'سعد',
    familyName: 'آل شايع',
    fatherId: 'P050',
    gender: 'Male',
    birthYear: 2018,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'سلطان بن عبدالرحمن بن خالد آل شايع',
    fullNameEn: 'Sultan bin Abdulrahman bin Khalid Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P069',
    firstName: 'ليان',
    fatherName: 'عبدالرحمن',
    grandfatherName: 'خالد',
    greatGrandfatherName: 'سعد',
    familyName: 'آل شايع',
    fatherId: 'P050',
    gender: 'Female',
    birthYear: 2020,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'ليان بنت عبدالرحمن بن خالد آل شايع',
    fullNameEn: 'Layan bint Abdulrahman bin Khalid Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P070',
    firstName: 'فيصل',
    fatherName: 'ناصر',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'سعد',
    familyName: 'آل شايع',
    fatherId: 'P052',
    gender: 'Male',
    birthYear: 2020,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'فيصل بن ناصر بن محمد آل شايع',
    fullNameEn: 'Faisal bin Nasser bin Mohammed Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P071',
    firstName: 'رزان',
    fatherName: 'ناصر',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'سعد',
    familyName: 'آل شايع',
    fatherId: 'P052',
    gender: 'Female',
    birthYear: 2022,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'رزان بنت ناصر بن محمد آل شايع',
    fullNameEn: 'Razan bint Nasser bin Mohammed Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P072',
    firstName: 'عبدالله',
    fatherName: 'فهد',
    grandfatherName: 'عبدالله',
    greatGrandfatherName: 'فيصل',
    familyName: 'آل شايع',
    fatherId: 'P054',
    gender: 'Male',
    birthYear: 2021,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'عبدالله بن فهد بن عبدالله آل شايع',
    fullNameEn: 'Abdullah bin Fahad bin Abdullah Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P073',
    firstName: 'يارا',
    fatherName: 'عبدالعزيز',
    grandfatherName: 'يزيد',
    greatGrandfatherName: 'طلال',
    familyName: 'آل شايع',
    fatherId: 'P060',
    gender: 'Female',
    birthYear: 2020,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'يارا بنت عبدالعزيز بن يزيد آل شايع',
    fullNameEn: 'Yara bint Abdulaziz bin Yazeed Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P074',
    firstName: 'مشعل',
    fatherName: 'عبدالعزيز',
    grandfatherName: 'يزيد',
    greatGrandfatherName: 'طلال',
    familyName: 'آل شايع',
    fatherId: 'P060',
    gender: 'Male',
    birthYear: 2022,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'مشعل بن عبدالعزيز بن يزيد آل شايع',
    fullNameEn: 'Mishal bin Abdulaziz bin Yazeed Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P075',
    firstName: 'تالا',
    fatherName: 'زياد',
    grandfatherName: 'مشاري',
    greatGrandfatherName: 'حسن',
    familyName: 'آل شايع',
    fatherId: 'P064',
    gender: 'Female',
    birthYear: 2021,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'تالا بنت زياد بن مشاري آل شايع',
    fullNameEn: 'Tala bint Ziyad bin Mishari Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },

  // Additional members (76-99)
  {
    id: 'P076',
    firstName: 'منصور',
    fatherName: 'سعد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P026',
    gender: 'Male',
    birthYear: 1960,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'منصور بن سعد بن ابراهيم آل شايع',
    fullNameEn: 'Mansour bin Saad bin Ibrahim Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'متقاعد',
    email: null,
  },
  {
    id: 'P077',
    firstName: 'هند',
    fatherName: 'سعد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P026',
    gender: 'Female',
    birthYear: 1963,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'هند بنت سعد بن ابراهيم آل شايع',
    fullNameEn: 'Hind bint Saad bin Ibrahim Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P078',
    firstName: 'عايض',
    fatherName: 'فيصل',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P027',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'عايض بن فيصل بن ابراهيم آل شايع',
    fullNameEn: 'Ayed bin Faisal bin Ibrahim Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'تاجر',
    email: null,
  },
  {
    id: 'P079',
    firstName: 'مها',
    fatherName: 'فيصل',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P027',
    gender: 'Female',
    birthYear: 1971,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'مها بنت فيصل بن ابراهيم آل شايع',
    fullNameEn: 'Maha bint Faisal bin Ibrahim Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P080',
    firstName: 'راشد',
    fatherName: 'ماجد',
    grandfatherName: 'عبدالمحسن',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P031',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'راشد بن ماجد بن عبدالمحسن آل شايع',
    fullNameEn: 'Rashid bin Majed bin Abdulmohsen Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'أستاذ جامعي',
    email: null,
  },
  {
    id: 'P081',
    firstName: 'أروى',
    fatherName: 'ماجد',
    grandfatherName: 'عبدالمحسن',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P031',
    gender: 'Female',
    birthYear: 1972,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'أروى بنت ماجد بن عبدالمحسن آل شايع',
    fullNameEn: 'Arwa bint Majed bin Abdulmohsen Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P082',
    firstName: 'هاني',
    fatherName: 'وليد',
    grandfatherName: 'عبدالرحمن',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P032',
    gender: 'Male',
    birthYear: 1972,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'هاني بن وليد بن عبدالرحمن آل شايع',
    fullNameEn: 'Hani bin Waleed bin Abdulrahman Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مدير عام',
    email: null,
  },
  {
    id: 'P083',
    firstName: 'ايمان',
    fatherName: 'وليد',
    grandfatherName: 'عبدالرحمن',
    greatGrandfatherName: 'محمد',
    familyName: 'آل شايع',
    fatherId: 'P032',
    gender: 'Female',
    birthYear: 1975,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'ايمان بنت وليد بن عبدالرحمن آل شايع',
    fullNameEn: 'Iman bint Waleed bin Abdulrahman Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P084',
    firstName: 'سامي',
    fatherName: 'طلال',
    grandfatherName: 'أحمد',
    greatGrandfatherName: 'ناصر',
    familyName: 'آل شايع',
    fatherId: 'P033',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'سامي بن طلال بن أحمد آل شايع',
    fullNameEn: 'Sami bin Talal bin Ahmed Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'ضابط',
    email: null,
  },
  {
    id: 'P085',
    firstName: 'آلاء',
    fatherName: 'نواف',
    grandfatherName: 'عبدالعزيز',
    greatGrandfatherName: 'ناصر',
    familyName: 'آل شايع',
    fatherId: 'P034',
    gender: 'Female',
    birthYear: 1975,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'آلاء بنت نواف بن عبدالعزيز آل شايع',
    fullNameEn: 'Alaa bint Nawaf bin Abdulaziz Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P086',
    firstName: 'ياسر',
    fatherName: 'حسن',
    grandfatherName: 'يوسف',
    greatGrandfatherName: 'سعود',
    familyName: 'آل شايع',
    fatherId: 'P035',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'ياسر بن حسن بن يوسف آل شايع',
    fullNameEn: 'Yasser bin Hassan bin Yousef Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'استشاري',
    email: null,
  },
  {
    id: 'P087',
    firstName: 'نادية',
    fatherName: 'عمر',
    grandfatherName: 'علي',
    greatGrandfatherName: 'سلمان',
    familyName: 'آل شايع',
    fatherId: 'P036',
    gender: 'Female',
    birthYear: 1973,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'نادية بنت عمر بن علي آل شايع',
    fullNameEn: 'Nadia bint Omar bin Ali Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P088',
    firstName: 'ثامر',
    fatherName: 'سلطان',
    grandfatherName: 'فهد',
    greatGrandfatherName: 'تركي',
    familyName: 'آل شايع',
    fatherId: 'P037',
    gender: 'Male',
    birthYear: 1978,
    sonsCount: 2,
    daughtersCount: 3,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'ثامر بن سلطان بن فهد آل شايع',
    fullNameEn: 'Thamer bin Sultan bin Fahad Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مهندس',
    email: null,
  },
  {
    id: 'P089',
    firstName: 'هدى',
    fatherName: 'سلطان',
    grandfatherName: 'فهد',
    greatGrandfatherName: 'تركي',
    familyName: 'آل شايع',
    fatherId: 'P037',
    gender: 'Female',
    birthYear: 1982,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'هدى بنت سلطان بن فهد آل شايع',
    fullNameEn: 'Huda bint Sultan bin Fahad Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P090',
    firstName: 'عبدالملك',
    fatherName: 'منصور',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P076',
    gender: 'Male',
    birthYear: 1988,
    sonsCount: 2,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'عبدالملك بن منصور بن سعد آل شايع',
    fullNameEn: 'Abdulmalik bin Mansour bin Saad Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مدير مشاريع',
    email: null,
  },
  {
    id: 'P091',
    firstName: 'وجدان',
    fatherName: 'عايض',
    grandfatherName: 'فيصل',
    greatGrandfatherName: 'ابراهيم',
    familyName: 'آل شايع',
    fatherId: 'P078',
    gender: 'Female',
    birthYear: 1993,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'وجدان بنت عايض بن فيصل آل شايع',
    fullNameEn: 'Wijdan bint Ayed bin Faisal Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'مهندسة',
    email: null,
  },
  {
    id: 'P092',
    firstName: 'عمار',
    fatherName: 'راشد',
    grandfatherName: 'ماجد',
    greatGrandfatherName: 'عبدالمحسن',
    familyName: 'آل شايع',
    fatherId: 'P080',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'عمار بن راشد بن ماجد آل شايع',
    fullNameEn: 'Ammar bin Rashid bin Majed Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'محاسب',
    email: null,
  },
  {
    id: 'P093',
    firstName: 'ديما',
    fatherName: 'هاني',
    grandfatherName: 'وليد',
    greatGrandfatherName: 'عبدالرحمن',
    familyName: 'آل شايع',
    fatherId: 'P082',
    gender: 'Female',
    birthYear: 1998,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'ديما بنت هاني بن وليد آل شايع',
    fullNameEn: 'Dima bint Hani bin Waleed Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالبة جامعية',
    email: null,
  },
  {
    id: 'P094',
    firstName: 'سالم',
    fatherName: 'سامي',
    grandfatherName: 'طلال',
    greatGrandfatherName: 'أحمد',
    familyName: 'آل شايع',
    fatherId: 'P084',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'سالم بن سامي بن طلال آل شايع',
    fullNameEn: 'Salem bin Sami bin Talal Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'ضابط',
    email: null,
  },
  {
    id: 'P095',
    firstName: 'لولوة',
    fatherName: 'ياسر',
    grandfatherName: 'حسن',
    greatGrandfatherName: 'يوسف',
    familyName: 'آل شايع',
    fatherId: 'P086',
    gender: 'Female',
    birthYear: 1996,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'لولوة بنت ياسر بن حسن آل شايع',
    fullNameEn: 'Loulwa bint Yasser bin Hassan Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طبيبة',
    email: null,
  },
  {
    id: 'P096',
    firstName: 'وائل',
    fatherName: 'ثامر',
    grandfatherName: 'سلطان',
    greatGrandfatherName: 'فهد',
    familyName: 'آل شايع',
    fatherId: 'P088',
    gender: 'Male',
    birthYear: 2005,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الفرع 1',
    fullNameAr: 'وائل بن ثامر بن سلطان آل شايع',
    fullNameEn: 'Wael bin Thamer bin Sultan Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: 'طالب',
    email: null,
  },
  {
    id: 'P097',
    firstName: 'نوف',
    fatherName: 'ثامر',
    grandfatherName: 'سلطان',
    greatGrandfatherName: 'فهد',
    familyName: 'آل شايع',
    fatherId: 'P088',
    gender: 'Female',
    birthYear: 2008,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الفرع 1',
    fullNameAr: 'نوف بنت ثامر بن سلطان آل شايع',
    fullNameEn: 'Nouf bint Thamer bin Sultan Al-Shaye',
    phone: null,
    city: 'جدة',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P098',
    firstName: 'جاسم',
    fatherName: 'عبدالملك',
    grandfatherName: 'منصور',
    greatGrandfatherName: 'سعد',
    familyName: 'آل شايع',
    fatherId: 'P090',
    gender: 'Male',
    birthYear: 2018,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'جاسم بن عبدالملك بن منصور آل شايع',
    fullNameEn: 'Jasem bin Abdulmalik bin Mansour Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
  {
    id: 'P099',
    firstName: 'حور',
    fatherName: 'سالم',
    grandfatherName: 'سامي',
    greatGrandfatherName: 'طلال',
    familyName: 'آل شايع',
    fatherId: 'P094',
    gender: 'Female',
    birthYear: 2021,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'حور بنت سالم بن سامي آل شايع',
    fullNameEn: 'Hoor bint Salem bin Sami Al-Shaye',
    phone: null,
    city: 'الرياض',
    status: 'Living',
    photoUrl: null,
    biography: null,
    occupation: null,
    email: null,
  },
];

// Helper function to calculate lineage for a member
function calculateLineageForMember(member: FamilyMember): FamilyMember {
  // Get lineage path (ancestor IDs from root to parent)
  const path: string[] = [];
  let current = familyMembers.find((m) => m.id === member.fatherId);
  while (current) {
    path.unshift(current.id);
    current = familyMembers.find((m) => m.id === current!.fatherId);
  }

  // Find Gen 2 ancestor (main branch founder)
  let gen2Ancestor: FamilyMember | null = null;
  if (member.generation === 1) {
    gen2Ancestor = null; // Root has no Gen 2 ancestor
  } else if (member.generation === 2) {
    gen2Ancestor = member; // Gen 2 members ARE the branch founders
  } else {
    // Find the Gen 2 ancestor in the path
    for (const ancestorId of path) {
      const ancestor = familyMembers.find((m) => m.id === ancestorId);
      if (ancestor && ancestor.generation === 2) {
        gen2Ancestor = ancestor;
        break;
      }
    }
  }

  // Find Gen 3 ancestor (sub-branch founder)
  let gen3Ancestor: FamilyMember | null = null;
  if (member.generation <= 2) {
    gen3Ancestor = null; // Gen 1-2 have no Gen 3 ancestor
  } else if (member.generation === 3) {
    gen3Ancestor = member; // Gen 3 members ARE the sub-branch founders
  } else {
    // Find the Gen 3 ancestor in the path
    for (const ancestorId of path) {
      const ancestor = familyMembers.find((m) => m.id === ancestorId);
      if (ancestor && ancestor.generation === 3) {
        gen3Ancestor = ancestor;
        break;
      }
    }
  }

  return {
    ...member,
    lineageBranchId: gen2Ancestor?.id || null,
    lineageBranchName: gen2Ancestor?.firstName || null,
    subBranchId: gen3Ancestor?.id || null,
    subBranchName: gen3Ancestor?.firstName || null,
    lineagePath: path,
  };
}

// Cache for members with lineage info
let membersWithLineage: FamilyMember[] | null = null;

// Helper functions to work with the data
export function getAllMembers(): FamilyMember[] {
  // Return cached version if available
  if (membersWithLineage) return membersWithLineage;

  // Calculate and cache lineage info for all members
  membersWithLineage = familyMembers.map(calculateLineageForMember);
  return membersWithLineage;
}

// Get raw members without lineage calculation (for internal use)
export function getRawMembers(): FamilyMember[] {
  return familyMembers;
}

export function getMemberById(id: string): FamilyMember | undefined {
  return familyMembers.find((m) => m.id === id);
}

export function getMaleMembers(): FamilyMember[] {
  return familyMembers.filter((m) => m.gender === 'Male');
}

export function getFemaleMembers(): FamilyMember[] {
  return familyMembers.filter((m) => m.gender === 'Female');
}

export function getMembersByGeneration(generation: number): FamilyMember[] {
  return familyMembers.filter((m) => m.generation === generation);
}

export function getMembersByBranch(branch: string): FamilyMember[] {
  return familyMembers.filter((m) => m.branch === branch);
}

export function getChildren(parentId: string): FamilyMember[] {
  return familyMembers.filter((m) => m.fatherId === parentId);
}

export function getStatistics() {
  const totalMembers = familyMembers.length;
  const males = familyMembers.filter((m) => m.gender === 'Male').length;
  const females = familyMembers.filter((m) => m.gender === 'Female').length;
  const generations = Math.max(...familyMembers.map((m) => m.generation));

  const branches = [...new Set(familyMembers.map((m) => m.branch).filter(Boolean))];
  const branchCounts = branches.map((branch) => ({
    name: branch,
    count: familyMembers.filter((m) => m.branch === branch).length,
  }));

  const generationBreakdown = Array.from({ length: generations }, (_, i) => {
    const gen = i + 1;
    const members = familyMembers.filter((m) => m.generation === gen);
    return {
      generation: gen,
      count: members.length,
      males: members.filter((m) => m.gender === 'Male').length,
      females: members.filter((m) => m.gender === 'Female').length,
      percentage: Math.round((members.length / totalMembers) * 100),
    };
  });

  return {
    totalMembers,
    males,
    females,
    generations,
    branches: branchCounts,
    generationBreakdown,
  };
}

export function buildFamilyTree(): FamilyMember & { children: FamilyMember[] } | null {
  const root = familyMembers.find((m) => !m.fatherId);
  if (!root) return null;

  const addChildren = (member: FamilyMember): FamilyMember & { children: any[] } => {
    const children = familyMembers.filter((m) => m.fatherId === member.id);
    return {
      ...member,
      children: children.map((child) => addChildren(child)),
    };
  };

  return addChildren(root);
}

export function getNextId(): string {
  const maxId = Math.max(...familyMembers.map((m) => parseInt(m.id.replace('P', ''))));
  return `P${String(maxId + 1).padStart(3, '0')}`;
}

// ============================================
// LINEAGE HELPER FUNCTIONS
// ============================================

/**
 * Get all Gen 2 members (main branch founders)
 * These are the direct children of the family founder
 */
export function getGen2Branches(): FamilyMember[] {
  const members = getAllMembers();
  return members.filter((m) => m.generation === 2);
}

/**
 * Get all Gen 3 members (sub-branch founders)
 * These are grandchildren of the family founder
 */
export function getGen3SubBranches(): FamilyMember[] {
  const members = getAllMembers();
  return members.filter((m) => m.generation === 3);
}

/**
 * Get all members belonging to a specific Gen 2 branch
 */
export function getMembersByLineageBranch(gen2AncestorId: string): FamilyMember[] {
  const members = getAllMembers();
  return members.filter((m) => m.lineageBranchId === gen2AncestorId);
}

/**
 * Get all members belonging to a specific Gen 3 sub-branch
 */
export function getMembersBySubBranch(gen3AncestorId: string): FamilyMember[] {
  const members = getAllMembers();
  return members.filter((m) => m.subBranchId === gen3AncestorId);
}

/**
 * Get lineage statistics for all Gen 2 branches
 */
export function getLineageStatistics() {
  const members = getAllMembers();
  const gen2Branches = getGen2Branches();

  const branchStats = gen2Branches.map((branch) => {
    const branchMembers = members.filter((m) => m.lineageBranchId === branch.id);
    const livingCount = branchMembers.filter((m) => m.status === 'Living').length;
    const maleCount = branchMembers.filter((m) => m.gender === 'Male').length;
    const femaleCount = branchMembers.filter((m) => m.gender === 'Female').length;

    // Get sub-branches for this Gen 2 branch
    const subBranches = branchMembers.filter((m) => m.generation === 3);

    return {
      id: branch.id,
      name: branch.firstName,
      fullName: branch.fullNameAr,
      totalCount: branchMembers.length,
      livingCount,
      maleCount,
      femaleCount,
      subBranchCount: subBranches.length,
      subBranches: subBranches.map((sb) => ({
        id: sb.id,
        name: sb.firstName,
        count: members.filter((m) => m.subBranchId === sb.id).length,
      })),
    };
  });

  return {
    totalBranches: gen2Branches.length,
    branches: branchStats,
  };
}

/**
 * Update a member in the in-memory array
 * Returns the updated member or null if not found
 */
export function updateMemberInMemory(id: string, updates: Partial<FamilyMember>): FamilyMember | null {
  const index = familyMembers.findIndex(m => m.id === id);
  if (index === -1) return null;

  // Merge updates with existing member
  familyMembers[index] = {
    ...familyMembers[index],
    ...updates,
    id, // Ensure ID is never changed
  };

  return familyMembers[index];
}

/**
 * Delete a member from the in-memory array
 * Returns true if deleted, false if not found
 */
export function deleteMemberFromMemory(id: string): boolean {
  const index = familyMembers.findIndex(m => m.id === id);
  if (index === -1) return false;

  familyMembers.splice(index, 1);
  return true;
}

/**
 * Add a new member to the in-memory array
 * Returns the added member
 */
export function addMemberToMemory(member: FamilyMember): FamilyMember {
  familyMembers.push(member);
  return member;
}
