import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// آل شايع Family Data - 99 members across 8 generations
const familyMembers = [
  // Generation 1 (Root - الجذر)
  {
    id: 'P001',
    firstName: 'حمد',
    fatherName: null,
    grandfatherName: null,
    greatGrandfatherName: null,
    fatherId: null,
    gender: 'Male',
    birthYear: 1600,
    sonsCount: 3,
    daughtersCount: 0,
    generation: 1,
    branch: 'الأصل',
    fullNameAr: 'حمد آل شايع',
    fullNameEn: 'Hamad Al-Shaye',
    status: 'Deceased',
  },

  // Generation 2 (أبناء حمد)
  {
    id: 'P002',
    firstName: 'ابراهيم',
    fatherName: 'حمد',
    grandfatherName: null,
    greatGrandfatherName: null,
    fatherId: 'P001',
    gender: 'Male',
    birthYear: 1630,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 2,
    branch: 'الأصل',
    fullNameAr: 'ابراهيم بن حمد آل شايع',
    fullNameEn: 'Ibrahim bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P003',
    firstName: 'عبدالكريم',
    fatherName: 'حمد',
    grandfatherName: null,
    greatGrandfatherName: null,
    fatherId: 'P001',
    gender: 'Male',
    birthYear: 1635,
    sonsCount: 2,
    daughtersCount: 1,
    generation: 2,
    branch: 'الأصل',
    fullNameAr: 'عبدالكريم بن حمد آل شايع',
    fullNameEn: 'Abdulkareem bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P004',
    firstName: 'فوزان',
    fatherName: 'حمد',
    grandfatherName: null,
    greatGrandfatherName: null,
    fatherId: 'P001',
    gender: 'Male',
    birthYear: 1640,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 2,
    branch: 'الفرع 1',
    fullNameAr: 'فوزان بن حمد آل شايع',
    fullNameEn: 'Fawzan bin Hamad Al-Shaye',
    status: 'Deceased',
  },

  // Generation 3 (أحفاد حمد)
  {
    id: 'P005',
    firstName: 'محمد',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P002',
    gender: 'Male',
    birthYear: 1660,
    sonsCount: 5,
    daughtersCount: 3,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'محمد بن ابراهيم بن حمد آل شايع',
    fullNameEn: 'Mohammed bin Ibrahim bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P006',
    firstName: 'ناصر',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P002',
    gender: 'Male',
    birthYear: 1665,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'ناصر بن ابراهيم بن حمد آل شايع',
    fullNameEn: 'Nasser bin Ibrahim bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P007',
    firstName: 'عبدالله',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P002',
    gender: 'Male',
    birthYear: 1670,
    sonsCount: 3,
    daughtersCount: 4,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'عبدالله بن ابراهيم بن حمد آل شايع',
    fullNameEn: 'Abdullah bin Ibrahim bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P008',
    firstName: 'فاطمة',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P002',
    gender: 'Female',
    birthYear: 1668,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'فاطمة بنت ابراهيم بن حمد آل شايع',
    fullNameEn: 'Fatima bint Ibrahim bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P009',
    firstName: 'نورة',
    fatherName: 'ابراهيم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P002',
    gender: 'Female',
    birthYear: 1672,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'نورة بنت ابراهيم بن حمد آل شايع',
    fullNameEn: 'Noura bint Ibrahim bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P010',
    firstName: 'سعود',
    fatherName: 'عبدالكريم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P003',
    gender: 'Male',
    birthYear: 1665,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'سعود بن عبدالكريم بن حمد آل شايع',
    fullNameEn: 'Saud bin Abdulkareem bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P011',
    firstName: 'خالد',
    fatherName: 'عبدالكريم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P003',
    gender: 'Male',
    birthYear: 1670,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'خالد بن عبدالكريم بن حمد آل شايع',
    fullNameEn: 'Khalid bin Abdulkareem bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P012',
    firstName: 'موضي',
    fatherName: 'عبدالكريم',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P003',
    gender: 'Female',
    birthYear: 1668,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 3,
    branch: 'الأصل',
    fullNameAr: 'موضي بنت عبدالكريم بن حمد آل شايع',
    fullNameEn: 'Moudi bint Abdulkareem bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P013',
    firstName: 'سلمان',
    fatherName: 'فوزان',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P004',
    gender: 'Male',
    birthYear: 1670,
    sonsCount: 5,
    daughtersCount: 2,
    generation: 3,
    branch: 'الفرع 1',
    fullNameAr: 'سلمان بن فوزان بن حمد آل شايع',
    fullNameEn: 'Salman bin Fawzan bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P014',
    firstName: 'تركي',
    fatherName: 'فوزان',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P004',
    gender: 'Male',
    birthYear: 1675,
    sonsCount: 3,
    daughtersCount: 4,
    generation: 3,
    branch: 'الفرع 1',
    fullNameAr: 'تركي بن فوزان بن حمد آل شايع',
    fullNameEn: 'Turki bin Fawzan bin Hamad Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P015',
    firstName: 'منيرة',
    fatherName: 'فوزان',
    grandfatherName: 'حمد',
    greatGrandfatherName: null,
    fatherId: 'P004',
    gender: 'Female',
    birthYear: 1672,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 3,
    branch: 'الفرع 1',
    fullNameAr: 'منيرة بنت فوزان بن حمد آل شايع',
    fullNameEn: 'Munira bint Fawzan bin Hamad Al-Shaye',
    status: 'Deceased',
  },

  // Generation 4
  {
    id: 'P016',
    firstName: 'ابراهيم',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    fatherId: 'P005',
    gender: 'Male',
    birthYear: 1890,
    sonsCount: 5,
    daughtersCount: 3,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'ابراهيم بن محمد بن ابراهيم آل شايع',
    fullNameEn: 'Ibrahim bin Mohammed bin Ibrahim Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P017',
    firstName: 'عبدالمحسن',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    fatherId: 'P005',
    gender: 'Male',
    birthYear: 1895,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'عبدالمحسن بن محمد بن ابراهيم آل شايع',
    fullNameEn: 'Abdulmohsen bin Mohammed bin Ibrahim Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P018',
    firstName: 'عبدالرحمن',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    fatherId: 'P005',
    gender: 'Male',
    birthYear: 1900,
    sonsCount: 6,
    daughtersCount: 4,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'عبدالرحمن بن محمد بن ابراهيم آل شايع',
    fullNameEn: 'Abdulrahman bin Mohammed bin Ibrahim Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P019',
    firstName: 'صالح',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    fatherId: 'P005',
    gender: 'Male',
    birthYear: 1905,
    sonsCount: 3,
    daughtersCount: 5,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'صالح بن محمد بن ابراهيم آل شايع',
    fullNameEn: 'Saleh bin Mohammed bin Ibrahim Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P020',
    firstName: 'حصة',
    fatherName: 'محمد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    fatherId: 'P005',
    gender: 'Female',
    birthYear: 1892,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'حصة بنت محمد بن ابراهيم آل شايع',
    fullNameEn: 'Hessa bint Mohammed bin Ibrahim Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P021',
    firstName: 'أحمد',
    fatherName: 'ناصر',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    fatherId: 'P006',
    gender: 'Male',
    birthYear: 1895,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'أحمد بن ناصر بن ابراهيم آل شايع',
    fullNameEn: 'Ahmed bin Nasser bin Ibrahim Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P022',
    firstName: 'عبدالعزيز',
    fatherName: 'ناصر',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'حمد',
    fatherId: 'P006',
    gender: 'Male',
    birthYear: 1900,
    sonsCount: 5,
    daughtersCount: 2,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'عبدالعزيز بن ناصر بن ابراهيم آل شايع',
    fullNameEn: 'Abdulaziz bin Nasser bin Ibrahim Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P023',
    firstName: 'يوسف',
    fatherName: 'سعود',
    grandfatherName: 'عبدالكريم',
    greatGrandfatherName: 'حمد',
    fatherId: 'P010',
    gender: 'Male',
    birthYear: 1895,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 4,
    branch: 'الأصل',
    fullNameAr: 'يوسف بن سعود بن عبدالكريم آل شايع',
    fullNameEn: 'Yousef bin Saud bin Abdulkareem Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P024',
    firstName: 'علي',
    fatherName: 'سلمان',
    grandfatherName: 'فوزان',
    greatGrandfatherName: 'حمد',
    fatherId: 'P013',
    gender: 'Male',
    birthYear: 1900,
    sonsCount: 5,
    daughtersCount: 4,
    generation: 4,
    branch: 'الفرع 1',
    fullNameAr: 'علي بن سلمان بن فوزان آل شايع',
    fullNameEn: 'Ali bin Salman bin Fawzan Al-Shaye',
    status: 'Deceased',
  },
  {
    id: 'P025',
    firstName: 'فهد',
    fatherName: 'تركي',
    grandfatherName: 'فوزان',
    greatGrandfatherName: 'حمد',
    fatherId: 'P014',
    gender: 'Male',
    birthYear: 1905,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 4,
    branch: 'الفرع 1',
    fullNameAr: 'فهد بن تركي بن فوزان آل شايع',
    fullNameEn: 'Fahad bin Turki bin Fawzan Al-Shaye',
    status: 'Deceased',
  },

  // Generation 5
  {
    id: 'P026',
    firstName: 'سعد',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P016',
    gender: 'Male',
    birthYear: 1935,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'سعد بن ابراهيم بن محمد آل شايع',
    fullNameEn: 'Saad bin Ibrahim bin Mohammed Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P027',
    firstName: 'فيصل',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P016',
    gender: 'Male',
    birthYear: 1940,
    sonsCount: 5,
    daughtersCount: 2,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'فيصل بن ابراهيم بن محمد آل شايع',
    fullNameEn: 'Faisal bin Ibrahim bin Mohammed Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P028',
    firstName: 'بندر',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P016',
    gender: 'Male',
    birthYear: 1945,
    sonsCount: 3,
    daughtersCount: 4,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'بندر بن ابراهيم بن محمد آل شايع',
    fullNameEn: 'Bandar bin Ibrahim bin Mohammed Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P029',
    firstName: 'سارة',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P016',
    gender: 'Female',
    birthYear: 1938,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'سارة بنت ابراهيم بن محمد آل شايع',
    fullNameEn: 'Sarah bint Ibrahim bin Mohammed Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P030',
    firstName: 'مريم',
    fatherName: 'ابراهيم',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P016',
    gender: 'Female',
    birthYear: 1942,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'مريم بنت ابراهيم بن محمد آل شايع',
    fullNameEn: 'Mariam bint Ibrahim bin Mohammed Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P031',
    firstName: 'ماجد',
    fatherName: 'عبدالمحسن',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P017',
    gender: 'Male',
    birthYear: 1940,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'ماجد بن عبدالمحسن بن محمد آل شايع',
    fullNameEn: 'Majed bin Abdulmohsen bin Mohammed Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P032',
    firstName: 'وليد',
    fatherName: 'عبدالرحمن',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P018',
    gender: 'Male',
    birthYear: 1945,
    sonsCount: 5,
    daughtersCount: 3,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'وليد بن عبدالرحمن بن محمد آل شايع',
    fullNameEn: 'Waleed bin Abdulrahman bin Mohammed Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P033',
    firstName: 'طلال',
    fatherName: 'أحمد',
    grandfatherName: 'ناصر',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P021',
    gender: 'Male',
    birthYear: 1940,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'طلال بن أحمد بن ناصر آل شايع',
    fullNameEn: 'Talal bin Ahmed bin Nasser Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P034',
    firstName: 'نواف',
    fatherName: 'عبدالعزيز',
    grandfatherName: 'ناصر',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P022',
    gender: 'Male',
    birthYear: 1945,
    sonsCount: 5,
    daughtersCount: 4,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'نواف بن عبدالعزيز بن ناصر آل شايع',
    fullNameEn: 'Nawaf bin Abdulaziz bin Nasser Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P035',
    firstName: 'حسن',
    fatherName: 'يوسف',
    grandfatherName: 'سعود',
    greatGrandfatherName: 'عبدالكريم',
    fatherId: 'P023',
    gender: 'Male',
    birthYear: 1940,
    sonsCount: 4,
    daughtersCount: 3,
    generation: 5,
    branch: 'الأصل',
    fullNameAr: 'حسن بن يوسف بن سعود آل شايع',
    fullNameEn: 'Hassan bin Yousef bin Saud Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P036',
    firstName: 'عمر',
    fatherName: 'علي',
    grandfatherName: 'سلمان',
    greatGrandfatherName: 'فوزان',
    fatherId: 'P024',
    gender: 'Male',
    birthYear: 1945,
    sonsCount: 5,
    daughtersCount: 3,
    generation: 5,
    branch: 'الفرع 1',
    fullNameAr: 'عمر بن علي بن سلمان آل شايع',
    fullNameEn: 'Omar bin Ali bin Salman Al-Shaye',
    status: 'Living',
  },
  {
    id: 'P037',
    firstName: 'سلطان',
    fatherName: 'فهد',
    grandfatherName: 'تركي',
    greatGrandfatherName: 'فوزان',
    fatherId: 'P025',
    gender: 'Male',
    birthYear: 1950,
    sonsCount: 4,
    daughtersCount: 4,
    generation: 5,
    branch: 'الفرع 1',
    fullNameAr: 'سلطان بن فهد بن تركي آل شايع',
    fullNameEn: 'Sultan bin Fahad bin Turki Al-Shaye',
    status: 'Living',
  },

  // Generation 6
  {
    id: 'P038',
    firstName: 'خالد',
    fatherName: 'سعد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P026',
    gender: 'Male',
    birthYear: 1965,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'خالد بن سعد بن ابراهيم آل شايع',
    fullNameEn: 'Khalid bin Saad bin Ibrahim Al-Shaye',
    status: 'Living',
    occupation: 'مهندس',
    city: 'الرياض',
  },
  {
    id: 'P039',
    firstName: 'محمد',
    fatherName: 'سعد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P026',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'محمد بن سعد بن ابراهيم آل شايع',
    fullNameEn: 'Mohammed bin Saad bin Ibrahim Al-Shaye',
    status: 'Living',
    occupation: 'طبيب',
    city: 'جدة',
  },
  {
    id: 'P040',
    firstName: 'عبدالله',
    fatherName: 'فيصل',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P027',
    gender: 'Male',
    birthYear: 1970,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'عبدالله بن فيصل بن ابراهيم آل شايع',
    fullNameEn: 'Abdullah bin Faisal bin Ibrahim Al-Shaye',
    status: 'Living',
    occupation: 'رجل أعمال',
    city: 'الرياض',
  },
  {
    id: 'P041',
    firstName: 'أمل',
    fatherName: 'فيصل',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P027',
    gender: 'Female',
    birthYear: 1972,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'أمل بنت فيصل بن ابراهيم آل شايع',
    fullNameEn: 'Amal bint Faisal bin Ibrahim Al-Shaye',
    status: 'Living',
    occupation: 'معلمة',
    city: 'الرياض',
  },
  {
    id: 'P042',
    firstName: 'عادل',
    fatherName: 'بندر',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P028',
    gender: 'Male',
    birthYear: 1975,
    sonsCount: 2,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'عادل بن بندر بن ابراهيم آل شايع',
    fullNameEn: 'Adel bin Bandar bin Ibrahim Al-Shaye',
    status: 'Living',
    occupation: 'محاسب',
    city: 'الدمام',
  },
  {
    id: 'P043',
    firstName: 'ريم',
    fatherName: 'ماجد',
    grandfatherName: 'عبدالمحسن',
    greatGrandfatherName: 'محمد',
    fatherId: 'P031',
    gender: 'Female',
    birthYear: 1970,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'ريم بنت ماجد بن عبدالمحسن آل شايع',
    fullNameEn: 'Reem bint Majed bin Abdulmohsen Al-Shaye',
    status: 'Living',
    occupation: 'طبيبة',
    city: 'الرياض',
  },
  {
    id: 'P044',
    firstName: 'فارس',
    fatherName: 'وليد',
    grandfatherName: 'عبدالرحمن',
    greatGrandfatherName: 'محمد',
    fatherId: 'P032',
    gender: 'Male',
    birthYear: 1975,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'فارس بن وليد بن عبدالرحمن آل شايع',
    fullNameEn: 'Fares bin Waleed bin Abdulrahman Al-Shaye',
    status: 'Living',
    occupation: 'مهندس',
    city: 'الرياض',
  },
  {
    id: 'P045',
    firstName: 'يزيد',
    fatherName: 'طلال',
    grandfatherName: 'أحمد',
    greatGrandfatherName: 'ناصر',
    fatherId: 'P033',
    gender: 'Male',
    birthYear: 1970,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'يزيد بن طلال بن أحمد آل شايع',
    fullNameEn: 'Yazeed bin Talal bin Ahmed Al-Shaye',
    status: 'Living',
    occupation: 'طيار',
    city: 'جدة',
  },
  {
    id: 'P046',
    firstName: 'تركي',
    fatherName: 'نواف',
    grandfatherName: 'عبدالعزيز',
    greatGrandfatherName: 'ناصر',
    fatherId: 'P034',
    gender: 'Male',
    birthYear: 1975,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'تركي بن نواف بن عبدالعزيز آل شايع',
    fullNameEn: 'Turki bin Nawaf bin Abdulaziz Al-Shaye',
    status: 'Living',
    occupation: 'محامي',
    city: 'الرياض',
  },
  {
    id: 'P047',
    firstName: 'مشاري',
    fatherName: 'حسن',
    grandfatherName: 'يوسف',
    greatGrandfatherName: 'سعود',
    fatherId: 'P035',
    gender: 'Male',
    birthYear: 1970,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'مشاري بن حسن بن يوسف آل شايع',
    fullNameEn: 'Mishari bin Hassan bin Yousef Al-Shaye',
    status: 'Living',
    occupation: 'مهندس معماري',
    city: 'الرياض',
  },
  {
    id: 'P048',
    firstName: 'راكان',
    fatherName: 'عمر',
    grandfatherName: 'علي',
    greatGrandfatherName: 'سلمان',
    fatherId: 'P036',
    gender: 'Male',
    birthYear: 1975,
    sonsCount: 3,
    daughtersCount: 4,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'راكان بن عمر بن علي آل شايع',
    fullNameEn: 'Rakan bin Omar bin Ali Al-Shaye',
    status: 'Living',
    occupation: 'مدير تنفيذي',
    city: 'الرياض',
  },
  {
    id: 'P049',
    firstName: 'دانة',
    fatherName: 'سلطان',
    grandfatherName: 'فهد',
    greatGrandfatherName: 'تركي',
    fatherId: 'P037',
    gender: 'Female',
    birthYear: 1980,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'دانة بنت سلطان بن فهد آل شايع',
    fullNameEn: 'Dana bint Sultan bin Fahad Al-Shaye',
    status: 'Living',
    occupation: 'مصممة',
    city: 'جدة',
  },

  // Generation 7
  {
    id: 'P050',
    firstName: 'عبدالرحمن',
    fatherName: 'خالد',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P038',
    gender: 'Male',
    birthYear: 1990,
    sonsCount: 2,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'عبدالرحمن بن خالد بن سعد آل شايع',
    fullNameEn: 'Abdulrahman bin Khalid bin Saad Al-Shaye',
    status: 'Living',
    occupation: 'مبرمج',
    city: 'الرياض',
  },
  {
    id: 'P051',
    firstName: 'سلمى',
    fatherName: 'خالد',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P038',
    gender: 'Female',
    birthYear: 1992,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'سلمى بنت خالد بن سعد آل شايع',
    fullNameEn: 'Salma bint Khalid bin Saad Al-Shaye',
    status: 'Living',
    occupation: 'مهندسة',
    city: 'الرياض',
  },
  {
    id: 'P052',
    firstName: 'ناصر',
    fatherName: 'محمد',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P039',
    gender: 'Male',
    birthYear: 1993,
    sonsCount: 1,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'ناصر بن محمد بن سعد آل شايع',
    fullNameEn: 'Nasser bin Mohammed bin Saad Al-Shaye',
    status: 'Living',
    occupation: 'طبيب أسنان',
    city: 'جدة',
  },
  {
    id: 'P053',
    firstName: 'لمى',
    fatherName: 'محمد',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P039',
    gender: 'Female',
    birthYear: 1995,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'لمى بنت محمد بن سعد آل شايع',
    fullNameEn: 'Lama bint Mohammed bin Saad Al-Shaye',
    status: 'Living',
    occupation: 'صيدلانية',
    city: 'جدة',
  },
  {
    id: 'P054',
    firstName: 'فهد',
    fatherName: 'عبدالله',
    grandfatherName: 'فيصل',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P040',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'فهد بن عبدالله بن فيصل آل شايع',
    fullNameEn: 'Fahad bin Abdullah bin Faisal Al-Shaye',
    status: 'Living',
    occupation: 'رائد أعمال',
    city: 'الرياض',
  },
  {
    id: 'P055',
    firstName: 'نورة',
    fatherName: 'عبدالله',
    grandfatherName: 'فيصل',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P040',
    gender: 'Female',
    birthYear: 1997,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'نورة بنت عبدالله بن فيصل آل شايع',
    fullNameEn: 'Noura bint Abdullah bin Faisal Al-Shaye',
    status: 'Living',
    occupation: 'طالبة جامعية',
    city: 'الرياض',
  },
  {
    id: 'P056',
    firstName: 'سعود',
    fatherName: 'عادل',
    grandfatherName: 'بندر',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P042',
    gender: 'Male',
    birthYear: 2000,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'سعود بن عادل بن بندر آل شايع',
    fullNameEn: 'Saud bin Adel bin Bandar Al-Shaye',
    status: 'Living',
    occupation: 'طالب جامعي',
    city: 'الدمام',
  },
  {
    id: 'P057',
    firstName: 'جود',
    fatherName: 'عادل',
    grandfatherName: 'بندر',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P042',
    gender: 'Female',
    birthYear: 2002,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'جود بنت عادل بن بندر آل شايع',
    fullNameEn: 'Joud bint Adel bin Bandar Al-Shaye',
    status: 'Living',
    occupation: 'طالبة ثانوية',
    city: 'الدمام',
  },
  {
    id: 'P058',
    firstName: 'حمد',
    fatherName: 'فارس',
    grandfatherName: 'وليد',
    greatGrandfatherName: 'عبدالرحمن',
    fatherId: 'P044',
    gender: 'Male',
    birthYear: 2000,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'حمد بن فارس بن وليد آل شايع',
    fullNameEn: 'Hamad bin Fares bin Waleed Al-Shaye',
    status: 'Living',
    occupation: 'طالب جامعي',
    city: 'الرياض',
  },
  {
    id: 'P059',
    firstName: 'لين',
    fatherName: 'فارس',
    grandfatherName: 'وليد',
    greatGrandfatherName: 'عبدالرحمن',
    fatherId: 'P044',
    gender: 'Female',
    birthYear: 2002,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'لين بنت فارس بن وليد آل شايع',
    fullNameEn: 'Leen bint Fares bin Waleed Al-Shaye',
    status: 'Living',
    occupation: 'طالبة ثانوية',
    city: 'الرياض',
  },
  {
    id: 'P060',
    firstName: 'عبدالعزيز',
    fatherName: 'يزيد',
    grandfatherName: 'طلال',
    greatGrandfatherName: 'أحمد',
    fatherId: 'P045',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'عبدالعزيز بن يزيد بن طلال آل شايع',
    fullNameEn: 'Abdulaziz bin Yazeed bin Talal Al-Shaye',
    status: 'Living',
    occupation: 'طيار',
    city: 'جدة',
  },
  {
    id: 'P061',
    firstName: 'ريناد',
    fatherName: 'يزيد',
    grandfatherName: 'طلال',
    greatGrandfatherName: 'أحمد',
    fatherId: 'P045',
    gender: 'Female',
    birthYear: 1998,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'ريناد بنت يزيد بن طلال آل شايع',
    fullNameEn: 'Renad bint Yazeed bin Talal Al-Shaye',
    status: 'Living',
    occupation: 'مصممة جرافيك',
    city: 'جدة',
  },
  {
    id: 'P062',
    firstName: 'بدر',
    fatherName: 'تركي',
    grandfatherName: 'نواف',
    greatGrandfatherName: 'عبدالعزيز',
    fatherId: 'P046',
    gender: 'Male',
    birthYear: 2000,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'بدر بن تركي بن نواف آل شايع',
    fullNameEn: 'Badr bin Turki bin Nawaf Al-Shaye',
    status: 'Living',
    occupation: 'طالب جامعي',
    city: 'الرياض',
  },
  {
    id: 'P063',
    firstName: 'غادة',
    fatherName: 'تركي',
    grandfatherName: 'نواف',
    greatGrandfatherName: 'عبدالعزيز',
    fatherId: 'P046',
    gender: 'Female',
    birthYear: 2003,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'غادة بنت تركي بن نواف آل شايع',
    fullNameEn: 'Ghada bint Turki bin Nawaf Al-Shaye',
    status: 'Living',
    occupation: 'طالبة ثانوية',
    city: 'الرياض',
  },
  {
    id: 'P064',
    firstName: 'زياد',
    fatherName: 'مشاري',
    grandfatherName: 'حسن',
    greatGrandfatherName: 'يوسف',
    fatherId: 'P047',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'زياد بن مشاري بن حسن آل شايع',
    fullNameEn: 'Ziyad bin Mishari bin Hassan Al-Shaye',
    status: 'Living',
    occupation: 'مهندس مدني',
    city: 'الرياض',
  },
  {
    id: 'P065',
    firstName: 'هيفاء',
    fatherName: 'مشاري',
    grandfatherName: 'حسن',
    greatGrandfatherName: 'يوسف',
    fatherId: 'P047',
    gender: 'Female',
    birthYear: 1998,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'هيفاء بنت مشاري بن حسن آل شايع',
    fullNameEn: 'Haifa bint Mishari bin Hassan Al-Shaye',
    status: 'Living',
    occupation: 'معلمة',
    city: 'الرياض',
  },
  {
    id: 'P066',
    firstName: 'عمر',
    fatherName: 'راكان',
    grandfatherName: 'عمر',
    greatGrandfatherName: 'علي',
    fatherId: 'P048',
    gender: 'Male',
    birthYear: 2000,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الفرع 1',
    fullNameAr: 'عمر بن راكان بن عمر آل شايع',
    fullNameEn: 'Omar bin Rakan bin Omar Al-Shaye',
    status: 'Living',
    occupation: 'طالب جامعي',
    city: 'الرياض',
  },
  {
    id: 'P067',
    firstName: 'لجين',
    fatherName: 'راكان',
    grandfatherName: 'عمر',
    greatGrandfatherName: 'علي',
    fatherId: 'P048',
    gender: 'Female',
    birthYear: 2002,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الفرع 1',
    fullNameAr: 'لجين بنت راكان بن عمر آل شايع',
    fullNameEn: 'Lujain bint Rakan bin Omar Al-Shaye',
    status: 'Living',
    occupation: 'طالبة ثانوية',
    city: 'الرياض',
  },

  // Generation 8 (youngest generation)
  {
    id: 'P068',
    firstName: 'سلطان',
    fatherName: 'عبدالرحمن',
    grandfatherName: 'خالد',
    greatGrandfatherName: 'سعد',
    fatherId: 'P050',
    gender: 'Male',
    birthYear: 2018,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'سلطان بن عبدالرحمن بن خالد آل شايع',
    fullNameEn: 'Sultan bin Abdulrahman bin Khalid Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P069',
    firstName: 'ليان',
    fatherName: 'عبدالرحمن',
    grandfatherName: 'خالد',
    greatGrandfatherName: 'سعد',
    fatherId: 'P050',
    gender: 'Female',
    birthYear: 2020,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'ليان بنت عبدالرحمن بن خالد آل شايع',
    fullNameEn: 'Layan bint Abdulrahman bin Khalid Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P070',
    firstName: 'فيصل',
    fatherName: 'ناصر',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'سعد',
    fatherId: 'P052',
    gender: 'Male',
    birthYear: 2020,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'فيصل بن ناصر بن محمد آل شايع',
    fullNameEn: 'Faisal bin Nasser bin Mohammed Al-Shaye',
    status: 'Living',
    city: 'جدة',
  },
  {
    id: 'P071',
    firstName: 'رزان',
    fatherName: 'ناصر',
    grandfatherName: 'محمد',
    greatGrandfatherName: 'سعد',
    fatherId: 'P052',
    gender: 'Female',
    birthYear: 2022,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'رزان بنت ناصر بن محمد آل شايع',
    fullNameEn: 'Razan bint Nasser bin Mohammed Al-Shaye',
    status: 'Living',
    city: 'جدة',
  },
  {
    id: 'P072',
    firstName: 'عبدالله',
    fatherName: 'فهد',
    grandfatherName: 'عبدالله',
    greatGrandfatherName: 'فيصل',
    fatherId: 'P054',
    gender: 'Male',
    birthYear: 2021,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'عبدالله بن فهد بن عبدالله آل شايع',
    fullNameEn: 'Abdullah bin Fahad bin Abdullah Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P073',
    firstName: 'يارا',
    fatherName: 'عبدالعزيز',
    grandfatherName: 'يزيد',
    greatGrandfatherName: 'طلال',
    fatherId: 'P060',
    gender: 'Female',
    birthYear: 2020,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'يارا بنت عبدالعزيز بن يزيد آل شايع',
    fullNameEn: 'Yara bint Abdulaziz bin Yazeed Al-Shaye',
    status: 'Living',
    city: 'جدة',
  },
  {
    id: 'P074',
    firstName: 'مشعل',
    fatherName: 'عبدالعزيز',
    grandfatherName: 'يزيد',
    greatGrandfatherName: 'طلال',
    fatherId: 'P060',
    gender: 'Male',
    birthYear: 2022,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'مشعل بن عبدالعزيز بن يزيد آل شايع',
    fullNameEn: 'Mishal bin Abdulaziz bin Yazeed Al-Shaye',
    status: 'Living',
    city: 'جدة',
  },
  {
    id: 'P075',
    firstName: 'تالا',
    fatherName: 'زياد',
    grandfatherName: 'مشاري',
    greatGrandfatherName: 'حسن',
    fatherId: 'P064',
    gender: 'Female',
    birthYear: 2021,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'تالا بنت زياد بن مشاري آل شايع',
    fullNameEn: 'Tala bint Ziyad bin Mishari Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },

  // Additional members to reach ~99 members
  {
    id: 'P076',
    firstName: 'منصور',
    fatherName: 'سعد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P026',
    gender: 'Male',
    birthYear: 1960,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'منصور بن سعد بن ابراهيم آل شايع',
    fullNameEn: 'Mansour bin Saad bin Ibrahim Al-Shaye',
    status: 'Living',
    occupation: 'متقاعد',
    city: 'الرياض',
  },
  {
    id: 'P077',
    firstName: 'هند',
    fatherName: 'سعد',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P026',
    gender: 'Female',
    birthYear: 1963,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'هند بنت سعد بن ابراهيم آل شايع',
    fullNameEn: 'Hind bint Saad bin Ibrahim Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P078',
    firstName: 'عايض',
    fatherName: 'فيصل',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P027',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'عايض بن فيصل بن ابراهيم آل شايع',
    fullNameEn: 'Ayed bin Faisal bin Ibrahim Al-Shaye',
    status: 'Living',
    occupation: 'تاجر',
    city: 'الرياض',
  },
  {
    id: 'P079',
    firstName: 'مها',
    fatherName: 'فيصل',
    grandfatherName: 'ابراهيم',
    greatGrandfatherName: 'محمد',
    fatherId: 'P027',
    gender: 'Female',
    birthYear: 1971,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'مها بنت فيصل بن ابراهيم آل شايع',
    fullNameEn: 'Maha bint Faisal bin Ibrahim Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P080',
    firstName: 'راشد',
    fatherName: 'ماجد',
    grandfatherName: 'عبدالمحسن',
    greatGrandfatherName: 'محمد',
    fatherId: 'P031',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'راشد بن ماجد بن عبدالمحسن آل شايع',
    fullNameEn: 'Rashid bin Majed bin Abdulmohsen Al-Shaye',
    status: 'Living',
    occupation: 'أستاذ جامعي',
    city: 'الرياض',
  },
  {
    id: 'P081',
    firstName: 'أروى',
    fatherName: 'ماجد',
    grandfatherName: 'عبدالمحسن',
    greatGrandfatherName: 'محمد',
    fatherId: 'P031',
    gender: 'Female',
    birthYear: 1972,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'أروى بنت ماجد بن عبدالمحسن آل شايع',
    fullNameEn: 'Arwa bint Majed bin Abdulmohsen Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P082',
    firstName: 'هاني',
    fatherName: 'وليد',
    grandfatherName: 'عبدالرحمن',
    greatGrandfatherName: 'محمد',
    fatherId: 'P032',
    gender: 'Male',
    birthYear: 1972,
    sonsCount: 3,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'هاني بن وليد بن عبدالرحمن آل شايع',
    fullNameEn: 'Hani bin Waleed bin Abdulrahman Al-Shaye',
    status: 'Living',
    occupation: 'مدير عام',
    city: 'الرياض',
  },
  {
    id: 'P083',
    firstName: 'ايمان',
    fatherName: 'وليد',
    grandfatherName: 'عبدالرحمن',
    greatGrandfatherName: 'محمد',
    fatherId: 'P032',
    gender: 'Female',
    birthYear: 1975,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'ايمان بنت وليد بن عبدالرحمن آل شايع',
    fullNameEn: 'Iman bint Waleed bin Abdulrahman Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P084',
    firstName: 'سامي',
    fatherName: 'طلال',
    grandfatherName: 'أحمد',
    greatGrandfatherName: 'ناصر',
    fatherId: 'P033',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 4,
    daughtersCount: 2,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'سامي بن طلال بن أحمد آل شايع',
    fullNameEn: 'Sami bin Talal bin Ahmed Al-Shaye',
    status: 'Living',
    occupation: 'ضابط',
    city: 'الرياض',
  },
  {
    id: 'P085',
    firstName: 'آلاء',
    fatherName: 'نواف',
    grandfatherName: 'عبدالعزيز',
    greatGrandfatherName: 'ناصر',
    fatherId: 'P034',
    gender: 'Female',
    birthYear: 1975,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'آلاء بنت نواف بن عبدالعزيز آل شايع',
    fullNameEn: 'Alaa bint Nawaf bin Abdulaziz Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P086',
    firstName: 'ياسر',
    fatherName: 'حسن',
    grandfatherName: 'يوسف',
    greatGrandfatherName: 'سعود',
    fatherId: 'P035',
    gender: 'Male',
    birthYear: 1968,
    sonsCount: 3,
    daughtersCount: 3,
    generation: 6,
    branch: 'الأصل',
    fullNameAr: 'ياسر بن حسن بن يوسف آل شايع',
    fullNameEn: 'Yasser bin Hassan bin Yousef Al-Shaye',
    status: 'Living',
    occupation: 'استشاري',
    city: 'الرياض',
  },
  {
    id: 'P087',
    firstName: 'نادية',
    fatherName: 'عمر',
    grandfatherName: 'علي',
    greatGrandfatherName: 'سلمان',
    fatherId: 'P036',
    gender: 'Female',
    birthYear: 1973,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'نادية بنت عمر بن علي آل شايع',
    fullNameEn: 'Nadia bint Omar bin Ali Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P088',
    firstName: 'ثامر',
    fatherName: 'سلطان',
    grandfatherName: 'فهد',
    greatGrandfatherName: 'تركي',
    fatherId: 'P037',
    gender: 'Male',
    birthYear: 1978,
    sonsCount: 2,
    daughtersCount: 3,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'ثامر بن سلطان بن فهد آل شايع',
    fullNameEn: 'Thamer bin Sultan bin Fahad Al-Shaye',
    status: 'Living',
    occupation: 'مهندس',
    city: 'جدة',
  },
  {
    id: 'P089',
    firstName: 'هدى',
    fatherName: 'سلطان',
    grandfatherName: 'فهد',
    greatGrandfatherName: 'تركي',
    fatherId: 'P037',
    gender: 'Female',
    birthYear: 1982,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 6,
    branch: 'الفرع 1',
    fullNameAr: 'هدى بنت سلطان بن فهد آل شايع',
    fullNameEn: 'Huda bint Sultan bin Fahad Al-Shaye',
    status: 'Living',
    city: 'جدة',
  },
  {
    id: 'P090',
    firstName: 'عبدالملك',
    fatherName: 'منصور',
    grandfatherName: 'سعد',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P076',
    gender: 'Male',
    birthYear: 1988,
    sonsCount: 2,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'عبدالملك بن منصور بن سعد آل شايع',
    fullNameEn: 'Abdulmalik bin Mansour bin Saad Al-Shaye',
    status: 'Living',
    occupation: 'مدير مشاريع',
    city: 'الرياض',
  },
  {
    id: 'P091',
    firstName: 'وجدان',
    fatherName: 'عايض',
    grandfatherName: 'فيصل',
    greatGrandfatherName: 'ابراهيم',
    fatherId: 'P078',
    gender: 'Female',
    birthYear: 1993,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'وجدان بنت عايض بن فيصل آل شايع',
    fullNameEn: 'Wijdan bint Ayed bin Faisal Al-Shaye',
    status: 'Living',
    occupation: 'مهندسة',
    city: 'الرياض',
  },
  {
    id: 'P092',
    firstName: 'عمار',
    fatherName: 'راشد',
    grandfatherName: 'ماجد',
    greatGrandfatherName: 'عبدالمحسن',
    fatherId: 'P080',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'عمار بن راشد بن ماجد آل شايع',
    fullNameEn: 'Ammar bin Rashid bin Majed Al-Shaye',
    status: 'Living',
    occupation: 'محاسب',
    city: 'الرياض',
  },
  {
    id: 'P093',
    firstName: 'ديما',
    fatherName: 'هاني',
    grandfatherName: 'وليد',
    greatGrandfatherName: 'عبدالرحمن',
    fatherId: 'P082',
    gender: 'Female',
    birthYear: 1998,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'ديما بنت هاني بن وليد آل شايع',
    fullNameEn: 'Dima bint Hani bin Waleed Al-Shaye',
    status: 'Living',
    occupation: 'طالبة جامعية',
    city: 'الرياض',
  },
  {
    id: 'P094',
    firstName: 'سالم',
    fatherName: 'سامي',
    grandfatherName: 'طلال',
    greatGrandfatherName: 'أحمد',
    fatherId: 'P084',
    gender: 'Male',
    birthYear: 1995,
    sonsCount: 1,
    daughtersCount: 1,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'سالم بن سامي بن طلال آل شايع',
    fullNameEn: 'Salem bin Sami bin Talal Al-Shaye',
    status: 'Living',
    occupation: 'ضابط',
    city: 'الرياض',
  },
  {
    id: 'P095',
    firstName: 'لولوة',
    fatherName: 'ياسر',
    grandfatherName: 'حسن',
    greatGrandfatherName: 'يوسف',
    fatherId: 'P086',
    gender: 'Female',
    birthYear: 1996,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الأصل',
    fullNameAr: 'لولوة بنت ياسر بن حسن آل شايع',
    fullNameEn: 'Loulwa bint Yasser bin Hassan Al-Shaye',
    status: 'Living',
    occupation: 'طبيبة',
    city: 'الرياض',
  },
  {
    id: 'P096',
    firstName: 'وائل',
    fatherName: 'ثامر',
    grandfatherName: 'سلطان',
    greatGrandfatherName: 'فهد',
    fatherId: 'P088',
    gender: 'Male',
    birthYear: 2005,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الفرع 1',
    fullNameAr: 'وائل بن ثامر بن سلطان آل شايع',
    fullNameEn: 'Wael bin Thamer bin Sultan Al-Shaye',
    status: 'Living',
    occupation: 'طالب',
    city: 'جدة',
  },
  {
    id: 'P097',
    firstName: 'نوف',
    fatherName: 'ثامر',
    grandfatherName: 'سلطان',
    greatGrandfatherName: 'فهد',
    fatherId: 'P088',
    gender: 'Female',
    birthYear: 2008,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 7,
    branch: 'الفرع 1',
    fullNameAr: 'نوف بنت ثامر بن سلطان آل شايع',
    fullNameEn: 'Nouf bint Thamer bin Sultan Al-Shaye',
    status: 'Living',
    city: 'جدة',
  },
  {
    id: 'P098',
    firstName: 'جاسم',
    fatherName: 'عبدالملك',
    grandfatherName: 'منصور',
    greatGrandfatherName: 'سعد',
    fatherId: 'P090',
    gender: 'Male',
    birthYear: 2018,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'جاسم بن عبدالملك بن منصور آل شايع',
    fullNameEn: 'Jasem bin Abdulmalik bin Mansour Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
  {
    id: 'P099',
    firstName: 'حور',
    fatherName: 'سالم',
    grandfatherName: 'سامي',
    greatGrandfatherName: 'طلال',
    fatherId: 'P094',
    gender: 'Female',
    birthYear: 2021,
    sonsCount: 0,
    daughtersCount: 0,
    generation: 8,
    branch: 'الأصل',
    fullNameAr: 'حور بنت سالم بن سامي آل شايع',
    fullNameEn: 'Hoor bint Salem bin Sami Al-Shaye',
    status: 'Living',
    city: 'الرياض',
  },
];

// ============================================
// PERMISSION CATEGORIES
// ============================================
const permissionCategories = [
  { key: 'viewing', labelAr: 'العرض', labelEn: 'Viewing', displayOrder: 1 },
  { key: 'members', labelAr: 'إدارة الأعضاء', labelEn: 'Member Management', displayOrder: 2 },
  { key: 'data', labelAr: 'عمليات البيانات', labelEn: 'Data Operations', displayOrder: 3 },
  { key: 'users', labelAr: 'إدارة المستخدمين', labelEn: 'User Management', displayOrder: 4 },
  { key: 'settings', labelAr: 'إعدادات النظام', labelEn: 'System Settings', displayOrder: 5 },
  { key: 'backup', labelAr: 'النسخ الاحتياطي', labelEn: 'Backup', displayOrder: 6 },
  { key: 'audit', labelAr: 'المراجعة', labelEn: 'Audit', displayOrder: 7 },
];

// ============================================
// PERMISSIONS
// ============================================
const permissions = [
  // Viewing permissions
  { key: 'view_family_tree', labelAr: 'عرض شجرة العائلة', labelEn: 'View Family Tree', category: 'viewing', displayOrder: 1 },
  { key: 'view_member_profiles', labelAr: 'عرض ملفات الأعضاء', labelEn: 'View Member Profiles', category: 'viewing', displayOrder: 2 },
  { key: 'view_member_contact', labelAr: 'عرض معلومات الاتصال', labelEn: 'View Contact Info', category: 'viewing', displayOrder: 3 },
  { key: 'view_member_photos', labelAr: 'عرض صور الأعضاء', labelEn: 'View Member Photos', category: 'viewing', displayOrder: 4 },
  { key: 'view_analytics', labelAr: 'عرض الإحصائيات', labelEn: 'View Analytics', category: 'viewing', displayOrder: 5 },
  { key: 'view_change_history', labelAr: 'عرض سجل التغييرات', labelEn: 'View Change History', category: 'viewing', displayOrder: 6 },
  // Member management
  { key: 'add_member', labelAr: 'إضافة عضو', labelEn: 'Add Member', category: 'members', displayOrder: 7 },
  { key: 'edit_member', labelAr: 'تعديل عضو', labelEn: 'Edit Member', category: 'members', displayOrder: 8 },
  { key: 'delete_member', labelAr: 'حذف عضو', labelEn: 'Delete Member', category: 'members', displayOrder: 9 },
  { key: 'suggest_edit', labelAr: 'اقتراح تعديل', labelEn: 'Suggest Edit', category: 'members', displayOrder: 10 },
  { key: 'approve_pending_members', labelAr: 'الموافقة على الأعضاء', labelEn: 'Approve Pending Members', category: 'members', displayOrder: 11 },
  // Data operations
  { key: 'export_data', labelAr: 'تصدير البيانات', labelEn: 'Export Data', category: 'data', displayOrder: 12 },
  { key: 'import_data', labelAr: 'استيراد البيانات', labelEn: 'Import Data', category: 'data', displayOrder: 13 },
  { key: 'create_snapshot', labelAr: 'إنشاء نسخة احتياطية', labelEn: 'Create Snapshot', category: 'data', displayOrder: 14 },
  { key: 'restore_snapshot', labelAr: 'استعادة نسخة احتياطية', labelEn: 'Restore Snapshot', category: 'data', displayOrder: 15 },
  // User management
  { key: 'view_users', labelAr: 'عرض المستخدمين', labelEn: 'View Users', category: 'users', displayOrder: 16 },
  { key: 'invite_users', labelAr: 'دعوة مستخدمين', labelEn: 'Invite Users', category: 'users', displayOrder: 17 },
  { key: 'approve_access_requests', labelAr: 'الموافقة على طلبات الوصول', labelEn: 'Approve Access Requests', category: 'users', displayOrder: 18 },
  { key: 'change_user_roles', labelAr: 'تغيير أدوار المستخدمين', labelEn: 'Change User Roles', category: 'users', displayOrder: 19 },
  { key: 'disable_users', labelAr: 'تعطيل المستخدمين', labelEn: 'Disable Users', category: 'users', displayOrder: 20 },
  // System settings
  { key: 'manage_site_settings', labelAr: 'إدارة إعدادات الموقع', labelEn: 'Manage Site Settings', category: 'settings', displayOrder: 21 },
  { key: 'manage_privacy_settings', labelAr: 'إدارة إعدادات الخصوصية', labelEn: 'Manage Privacy Settings', category: 'settings', displayOrder: 22 },
  { key: 'manage_permission_matrix', labelAr: 'إدارة صلاحيات الأدوار', labelEn: 'Manage Permission Matrix', category: 'settings', displayOrder: 23 },
  { key: 'view_audit_logs', labelAr: 'عرض سجلات النظام', labelEn: 'View Audit Logs', category: 'audit', displayOrder: 24 },
  { key: 'manage_branch_links', labelAr: 'إدارة روابط الفروع', labelEn: 'Manage Branch Links', category: 'settings', displayOrder: 25 },
];

// ============================================
// ROLE DEFAULT PERMISSIONS MATRIX
// ============================================
const rolePermissionMatrix: Record<string, Record<string, boolean>> = {
  GUEST: {
    view_family_tree: true,
    view_member_profiles: false,
    view_member_contact: false,
    view_member_photos: false,
    view_analytics: false,
    view_change_history: false,
    add_member: false,
    edit_member: false,
    delete_member: false,
    suggest_edit: false,
    approve_pending_members: false,
    export_data: false,
    import_data: false,
    create_snapshot: false,
    restore_snapshot: false,
    view_users: false,
    invite_users: false,
    approve_access_requests: false,
    change_user_roles: false,
    disable_users: false,
    manage_site_settings: false,
    manage_privacy_settings: false,
    manage_permission_matrix: false,
    view_audit_logs: false,
    manage_branch_links: false,
  },
  MEMBER: {
    view_family_tree: true,
    view_member_profiles: true,
    view_member_contact: true,
    view_member_photos: true,
    view_analytics: true,
    view_change_history: false,
    add_member: false,
    edit_member: false,
    delete_member: false,
    suggest_edit: true,
    approve_pending_members: false,
    export_data: false,
    import_data: false,
    create_snapshot: false,
    restore_snapshot: false,
    view_users: false,
    invite_users: false,
    approve_access_requests: false,
    change_user_roles: false,
    disable_users: false,
    manage_site_settings: false,
    manage_privacy_settings: false,
    manage_permission_matrix: false,
    view_audit_logs: false,
    manage_branch_links: false,
  },
  BRANCH_LEADER: {
    view_family_tree: true,
    view_member_profiles: true,
    view_member_contact: true,
    view_member_photos: true,
    view_analytics: true,
    view_change_history: true,
    add_member: true,
    edit_member: true,
    delete_member: false,
    suggest_edit: true,
    approve_pending_members: true,
    export_data: false,
    import_data: false,
    create_snapshot: false,
    restore_snapshot: false,
    view_users: false,
    invite_users: true,
    approve_access_requests: false,
    change_user_roles: false,
    disable_users: false,
    manage_site_settings: false,
    manage_privacy_settings: false,
    manage_permission_matrix: false,
    view_audit_logs: false,
    manage_branch_links: true,
  },
  ADMIN: {
    view_family_tree: true,
    view_member_profiles: true,
    view_member_contact: true,
    view_member_photos: true,
    view_analytics: true,
    view_change_history: true,
    add_member: true,
    edit_member: true,
    delete_member: false,
    suggest_edit: true,
    approve_pending_members: true,
    export_data: true,
    import_data: false,
    create_snapshot: true,
    restore_snapshot: false,
    view_users: true,
    invite_users: true,
    approve_access_requests: true,
    change_user_roles: true,
    disable_users: false,
    manage_site_settings: false,
    manage_privacy_settings: false,
    manage_permission_matrix: false,
    view_audit_logs: true,
    manage_branch_links: true,
  },
  SUPER_ADMIN: {
    view_family_tree: true,
    view_member_profiles: true,
    view_member_contact: true,
    view_member_photos: true,
    view_analytics: true,
    view_change_history: true,
    add_member: true,
    edit_member: true,
    delete_member: true,
    suggest_edit: true,
    approve_pending_members: true,
    export_data: true,
    import_data: true,
    create_snapshot: true,
    restore_snapshot: true,
    view_users: true,
    invite_users: true,
    approve_access_requests: true,
    change_user_roles: true,
    disable_users: true,
    manage_site_settings: true,
    manage_privacy_settings: true,
    manage_permission_matrix: true,
    view_audit_logs: true,
    manage_branch_links: true,
  },
};

// ============================================
// EXPORT FIELD CATEGORIES
// ============================================
const exportFieldCategories = [
  { key: 'identity', labelEn: 'Identity', labelAr: 'الهوية', displayOrder: 1 },
  { key: 'family', labelEn: 'Family', labelAr: 'العائلة', displayOrder: 2 },
  { key: 'personal', labelEn: 'Personal', labelAr: 'شخصي', displayOrder: 3 },
  { key: 'contact', labelEn: 'Contact', labelAr: 'التواصل', displayOrder: 4 },
  { key: 'meta', labelEn: 'Metadata', labelAr: 'البيانات الوصفية', displayOrder: 5 },
];

// ============================================
// EXPORT FIELDS
// ============================================
const exportFields = [
  // Identity fields
  { key: 'id', labelEn: 'ID', labelAr: 'الرقم', category: 'identity', selectedByDefault: true, displayOrder: 1 },
  { key: 'firstName', labelEn: 'First Name', labelAr: 'الاسم الأول', category: 'identity', selectedByDefault: true, displayOrder: 2 },
  { key: 'fatherName', labelEn: 'Father Name', labelAr: 'اسم الأب', category: 'identity', selectedByDefault: true, displayOrder: 3 },
  { key: 'grandfatherName', labelEn: 'Grandfather Name', labelAr: 'اسم الجد', category: 'identity', selectedByDefault: true, displayOrder: 4 },
  { key: 'greatGrandfatherName', labelEn: 'Great Grandfather', labelAr: 'اسم الجد الثاني', category: 'identity', selectedByDefault: false, displayOrder: 5 },
  { key: 'familyName', labelEn: 'Family Name', labelAr: 'اسم العائلة', category: 'identity', selectedByDefault: true, displayOrder: 6 },
  { key: 'fullNameAr', labelEn: 'Full Name (Arabic)', labelAr: 'الاسم الكامل', category: 'identity', selectedByDefault: true, displayOrder: 7 },
  { key: 'fullNameEn', labelEn: 'Full Name (English)', labelAr: 'الاسم بالإنجليزية', category: 'identity', selectedByDefault: false, displayOrder: 8 },
  // Family fields
  { key: 'fatherId', labelEn: 'Father ID', labelAr: 'رقم الأب', category: 'family', selectedByDefault: true, displayOrder: 9 },
  { key: 'gender', labelEn: 'Gender', labelAr: 'الجنس', category: 'family', selectedByDefault: true, displayOrder: 10 },
  { key: 'generation', labelEn: 'Generation', labelAr: 'الجيل', category: 'family', selectedByDefault: true, displayOrder: 11 },
  { key: 'branch', labelEn: 'Branch', labelAr: 'الفرع', category: 'family', selectedByDefault: true, displayOrder: 12 },
  { key: 'sonsCount', labelEn: 'Sons Count', labelAr: 'عدد الأبناء', category: 'family', selectedByDefault: true, displayOrder: 13 },
  { key: 'daughtersCount', labelEn: 'Daughters Count', labelAr: 'عدد البنات', category: 'family', selectedByDefault: true, displayOrder: 14 },
  // Personal fields
  { key: 'birthYear', labelEn: 'Birth Year', labelAr: 'سنة الميلاد', category: 'personal', selectedByDefault: true, displayOrder: 15 },
  { key: 'deathYear', labelEn: 'Death Year', labelAr: 'سنة الوفاة', category: 'personal', selectedByDefault: false, displayOrder: 16 },
  { key: 'status', labelEn: 'Status', labelAr: 'الحالة', category: 'personal', selectedByDefault: true, displayOrder: 17 },
  { key: 'occupation', labelEn: 'Occupation', labelAr: 'المهنة', category: 'personal', selectedByDefault: true, displayOrder: 18 },
  { key: 'biography', labelEn: 'Biography', labelAr: 'السيرة', category: 'personal', selectedByDefault: false, displayOrder: 19 },
  { key: 'photoUrl', labelEn: 'Photo URL', labelAr: 'رابط الصورة', category: 'personal', selectedByDefault: false, displayOrder: 20 },
  // Contact fields
  { key: 'phone', labelEn: 'Phone', labelAr: 'الهاتف', category: 'contact', selectedByDefault: true, displayOrder: 21 },
  { key: 'email', labelEn: 'Email', labelAr: 'البريد', category: 'contact', selectedByDefault: true, displayOrder: 22 },
  { key: 'city', labelEn: 'City', labelAr: 'المدينة', category: 'contact', selectedByDefault: true, displayOrder: 23 },
];

// ============================================
// JOURNAL CATEGORIES
// ============================================
const journalCategories = [
  { key: 'ORAL_HISTORY', nameAr: 'الروايات الشفهية', nameEn: 'Oral History', icon: '📜', color: 'amber', displayOrder: 1 },
  { key: 'MIGRATION', nameAr: 'الهجرات والتنقلات', nameEn: 'Migration', icon: '🐪', color: 'orange', displayOrder: 2 },
  { key: 'MEMORY', nameAr: 'الذكريات', nameEn: 'Memories', icon: '💭', color: 'blue', displayOrder: 3 },
  { key: 'POEM', nameAr: 'الشعر والأدب', nameEn: 'Poetry', icon: '✒️', color: 'rose', displayOrder: 4 },
  { key: 'GENEALOGY', nameAr: 'الأنساب', nameEn: 'Genealogy', icon: '🌳', color: 'green', displayOrder: 5 },
];

// ============================================
// EVENT TYPES
// ============================================
const eventTypes = [
  { key: 'gathering', labelEn: 'Gathering', labelAr: 'لقاء', color: 'text-green-700', bgColor: 'bg-green-100', displayOrder: 1 },
  { key: 'wedding', labelEn: 'Wedding', labelAr: 'زفاف', color: 'text-pink-700', bgColor: 'bg-pink-100', displayOrder: 2 },
  { key: 'eid', labelEn: 'Eid', labelAr: 'عيد', color: 'text-amber-700', bgColor: 'bg-amber-100', displayOrder: 3 },
  { key: 'memorial', labelEn: 'Memorial', labelAr: 'ذكرى', color: 'text-gray-700', bgColor: 'bg-gray-100', displayOrder: 4 },
  { key: 'celebration', labelEn: 'Celebration', labelAr: 'احتفال', color: 'text-purple-700', bgColor: 'bg-purple-100', displayOrder: 5 },
];

// ============================================
// SAMPLE GATHERINGS
// ============================================
const sampleGatherings = [
  {
    title: 'Eid Al-Fitr Family Gathering',
    titleAr: 'لقاء عيد الفطر العائلي',
    description: 'Annual Eid gathering at the family estate. All family members are welcome!',
    descriptionAr: 'اللقاء السنوي للعيد في ديوانية العائلة. جميع أفراد العائلة مدعوون!',
    date: new Date('2025-03-30T10:00:00'),
    time: '10:00',
    location: 'Family Estate, Riyadh',
    locationAr: 'ديوانية العائلة، الرياض',
    type: 'eid',
    organizerName: 'Mohammed Al-Shaye',
    organizerNameAr: 'محمد آل شايع',
    status: 'UPCOMING',
  },
  {
    title: 'Ahmed & Sara Wedding',
    titleAr: 'زفاف أحمد وسارة',
    description: 'Join us in celebrating the wedding of Ahmed bin Khalid and Sara.',
    descriptionAr: 'شاركونا فرحة زفاف أحمد بن خالد وسارة.',
    date: new Date('2025-02-15T19:00:00'),
    time: '19:00',
    location: 'Ritz Carlton, Riyadh',
    locationAr: 'ريتز كارلتون، الرياض',
    type: 'wedding',
    organizerName: 'Khalid Al-Shaye',
    organizerNameAr: 'خالد آل شايع',
    status: 'UPCOMING',
  },
  {
    title: 'Monthly Family Dinner',
    titleAr: 'العشاء العائلي الشهري',
    description: 'Our monthly family dinner - great food, great company!',
    descriptionAr: 'عشاؤنا العائلي الشهري - طعام رائع وصحبة أروع!',
    date: new Date('2025-01-25T20:00:00'),
    time: '20:00',
    location: 'Al-Shaye House',
    locationAr: 'بيت آل شايع',
    type: 'gathering',
    organizerName: 'Fatima Al-Shaye',
    organizerNameAr: 'فاطمة آل شايع',
    status: 'UPCOMING',
  },
];

async function main() {
  console.log('🌳 Seeding آل شايع family database...');
  console.log(`📊 Total members to insert: ${familyMembers.length}`);

  // Clear existing data
  console.log('\n🗑️  Clearing existing data...');
  await prisma.gatheringAttendee.deleteMany();
  await prisma.gathering.deleteMany();
  await prisma.roleDefaultPermission.deleteMany();
  await prisma.permission.deleteMany();
  await prisma.permissionCategory.deleteMany();
  await prisma.exportField.deleteMany();
  await prisma.exportFieldCategory.deleteMany();
  await prisma.journalCategory.deleteMany();
  await prisma.eventType.deleteMany();
  await prisma.familyMember.deleteMany();

  // Insert family members
  console.log('\n👨‍👩‍👧‍👦 Inserting family members...');
  for (const member of familyMembers) {
    await prisma.familyMember.create({
      data: member,
    });
  }

  // Insert permission categories
  console.log('🔐 Inserting permission categories...');
  for (const cat of permissionCategories) {
    await prisma.permissionCategory.create({ data: cat });
  }

  // Insert permissions
  console.log('🔐 Inserting permissions...');
  const createdPermissions: Record<string, string> = {};
  for (const perm of permissions) {
    const created = await prisma.permission.create({ data: perm });
    createdPermissions[perm.key] = created.id;
  }

  // Insert role default permissions
  console.log('👥 Inserting role default permissions...');
  for (const [role, perms] of Object.entries(rolePermissionMatrix)) {
    for (const [permKey, allowed] of Object.entries(perms)) {
      const permissionId = createdPermissions[permKey];
      if (permissionId) {
        await prisma.roleDefaultPermission.create({
          data: {
            role,
            permissionId,
            allowed,
          },
        });
      }
    }
  }

  // Insert export field categories
  console.log('📤 Inserting export field categories...');
  for (const cat of exportFieldCategories) {
    await prisma.exportFieldCategory.create({ data: cat });
  }

  // Insert export fields
  console.log('📤 Inserting export fields...');
  for (const field of exportFields) {
    await prisma.exportField.create({ data: field });
  }

  // Insert journal categories
  console.log('📚 Inserting journal categories...');
  for (const cat of journalCategories) {
    await prisma.journalCategory.create({ data: cat });
  }

  // Insert event types
  console.log('🎉 Inserting event types...');
  for (const type of eventTypes) {
    await prisma.eventType.create({ data: type });
  }

  // Insert sample gatherings
  console.log('🎊 Inserting sample gatherings...');
  for (const gathering of sampleGatherings) {
    await prisma.gathering.create({ data: gathering });
  }

  // Create default site settings if not exists
  console.log('⚙️  Setting up site settings...');
  await prisma.siteSettings.upsert({
    where: { id: 'default' },
    update: {},
    create: {
      id: 'default',
      familyNameArabic: 'آل شايع',
      familyNameEnglish: 'Al-Shaye',
      taglineArabic: 'نحفظ إرثنا، نربط أجيالنا',
      taglineEnglish: 'Preserving Our Legacy, Connecting Generations',
    },
  });

  // Create default privacy settings if not exists
  console.log('🔒 Setting up privacy settings...');
  await prisma.privacySettings.upsert({
    where: { id: 'default' },
    update: {},
    create: {
      id: 'default',
    },
  });

  // Create default backup config if not exists
  console.log('💾 Setting up backup configuration...');
  await prisma.backupConfig.upsert({
    where: { id: 'default' },
    update: {},
    create: {
      id: 'default',
      enabled: true,
      intervalHours: 24,
      maxBackups: 10,
      retentionDays: 30,
    },
  });

  // Verify statistics
  const totalMembers = await prisma.familyMember.count();
  const males = await prisma.familyMember.count({ where: { gender: 'Male' } });
  const females = await prisma.familyMember.count({ where: { gender: 'Female' } });
  const totalPermissions = await prisma.permission.count();
  const totalExportFields = await prisma.exportField.count();
  const totalGatherings = await prisma.gathering.count();

  console.log('\n✅ Database seeded successfully!');
  console.log('📊 Statistics:');
  console.log(`   - Total members: ${totalMembers}`);
  console.log(`   - Males: ${males}`);
  console.log(`   - Females: ${females}`);
  console.log(`   - Permissions: ${totalPermissions}`);
  console.log(`   - Export fields: ${totalExportFields}`);
  console.log(`   - Gatherings: ${totalGatherings}`);
  console.log('\n🌳 شجرة آل شايع جاهزة!');
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
